### ISSUE TITLE
ipchicken.com, whaismyip.com, whatismyipaddress.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#10]
This website simply lists your public IP address
It is not spyware or adware. 
I believe this is a false positive
Thanks.

**Comment by ShadowWhisperer** [comment]
You are correct, they are not malicious. They are commonly used for _tracking_.
_icanhazip.com_ is another commonly used domain.  I have seen this one used in malicious code.
There are probably over 100 sites similar to those, that I added manually (not discovered with scripts).

**Comment by p1r473** [comment]
Tracking in what way? They just simply let you know your IP.

**Comment by p1r473** [comment]
Tracking in what way?

**Comment by ShadowWhisperer** [comment]
They are used to lookup your IP address and use 3rd party services to find your location.
