### ISSUE TITLE
more VPNs

### ISSUE THREAD

**Issue by az0** [ShadowWhisperer/BlockLists#103]
You may want to add these to your tunnel list

Windscribe and ProtonVPN
https://github.com/az0/vpn_ip/blob/main/data/hostname.txt

Windscribe uses many *.totallyacdn.com hostnames

Opera VPN
api.sec-tunnel.com
api2.sec-tunnel.com

AirVPN uses many *vpn.airdns.org

Proxies/proxy lists
www.proxysite.com
www.proxfree.com 
hide.me 
whoer.net
hidester.com 
www.hidemyass.com 
www.croxyproxy.com 
plainproxies.com

**Comment by ShadowWhisperer** [comment]
Added these, everything else is already blocked. Thanks!
```
airdns.org
plainproxies.com
totallyacdn.com
```

If you're looking for more IPs for your VPN IP list: https://raw.githubusercontent.com/ShadowWhisperer/IPs/master/Other/Tunnel
