### ISSUE TITLE
Invalid domain on list:

### ISSUE THREAD

**Issue by pallebone** [ShadowWhisperer/BlockLists#105]
Hi there,

Thank you for this list. i notice there is an invalid domain on the list:
  [i] Target: https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Ads
  [✓] Status: Retrieval successful
  [✓] Parsed 19030 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "e-peddler.c"

Kind regards
Pete

**Comment by ShadowWhisperer** [comment]
Removed. Thanks!

**Comment by pallebone** [comment]
Thanks :)
