### ISSUE TITLE
humordog.xyz

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#106]
Hey Shadow

do this domain `humordog.xyz` still have any relevance for the mal list?

https://0xacab.org/my-privacy-dns/matrix/-/issues/624419

**Comment by spirillen** [comment]
This one too: same screen `

**Comment by ShadowWhisperer** [comment]
Owned by **NoStopMedia** (If that's even a real company)
My notes: Abuses push notifications and seen pushing malicious links.

**Comment by spirillen** [comment]
Thk for your reply
