### ISSUE TITLE
Tracking: im-pres-sum.de + freenet-business.de

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#107]
im-pres-sum.de is almost as clean as a baby, if they haven's tried to include g fonts, so wondering why it is on your tracking list: https://0xacab.org/my-privacy-dns/matrix/-/issues/628576

`https://www.freenet-business.de/` https://0xacab.org/my-privacy-dns/matrix/-/issues/628543 seems to be using `https://matomo.fdknet.de/matomo.js` as tracking, not `freenet-business.de`

**Comment by spirillen** [comment]
This one too `https://industriekultur.berlin/` I'm not spotting any tracking, not even third party

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +19 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/uploads/Start_ewerk_c_Andreas-Muhs_berlinHistory-App-5-1024x517.jpg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/uploads/cropped-cropped-Logo-Industriekultur-Berlin-PFEIL-32x32.png` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/uploads/cropped-cropped-Logo-Industriekultur-Berlin-PFEIL-192x192.png` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/uploads/IER1825-1024x683.jpg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/uploads/8_rbb_Standort_Berlin-1024x585.jpg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/start-zier-2.svg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/start-zier-4-gold.svg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/uploads/HTW-Imagefotos-DSC215900-HTW-Berlin-Alexander-Rentsch-1024x682.jpg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/uploads/Slider-Schriftenreihe-Industriekultur-2-1024x427.jpg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/assets/img/bzi-logo.svg` |
| +12 |  |  | industriekultur.berlin | 1 | post | xhr | `https://industriekultur.berlin/wp-admin/admin-ajax.php` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/plugins/borlabs-cookie/assets/images/borlabs-cookie-icon-black.svg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/marker-schauplatz.svg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/marker.svg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/info-icon.svg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/popup-tooltip.svg` |
| +12 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/info-schauplatz.svg` |
| +12 |  |  | industriekultur.berlin | 3 | get | image | `https://tile.jawg.io/jawg-terrain/10/550/336.png?access-token=6kKHBAtNyPFM5vvm5zz2jf5M0BQbTtk57SN8okq19cSzMVyahzoojWgBhr9ctK6N` |
| +12 |  |  | industriekultur.berlin | 3 | get | image | `https://tile.jawg.io/jawg-terrain/10/549/336.png?access-token=6kKHBAtNyPFM5vvm5zz2jf5M0BQbTtk57SN8okq19cSzMVyahzoojWgBhr9ctK6N` |
| +12 |  |  | industriekultur.berlin | 3 | get | image | `https://tile.jawg.io/jawg-terrain/10/550/335.png?access-token=6kKHBAtNyPFM5vvm5zz2jf5M0BQbTtk57SN8okq19cSzMVyahzoojWgBhr9ctK6N` |
| +12 |  |  | industriekultur.berlin | 3 | get | image | `https://tile.jawg.io/jawg-terrain/10/549/335.png?access-token=6kKHBAtNyPFM5vvm5zz2jf5M0BQbTtk57SN8okq19cSzMVyahzoojWgBhr9ctK6N` |
| +12 |  |  | industriekultur.berlin | 1 | get | font | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/fonts/barlow-900.woff2` |
| +12 |  |  | industriekultur.berlin | 1 | get | font | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/fonts/barlow-600.woff2` |
| +12 |  |  | industriekultur.berlin | 1 | get | font | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/fonts/barlow-700.woff2` |
| +12 |  |  | industriekultur.berlin | 1 | get | font | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/fonts/barlow-500.woff2` |
| +11 |  |  | industriekultur.berlin | 1 | get | font | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/fonts/barlow-400.woff2` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/arrow-link.svg` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/newsletter-background.svg` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/nav-arrow-right-gold.svg` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/nav-arrow-right-active.svg` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/header-zier-2-gold.svg` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/nav-arrow-right.svg` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/nav-arrow-left.svg` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/search-icon.svg` |
| +11 |  |  | industriekultur.berlin | 1 | get | image | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/img/search-zier.svg` |
| +7 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/print.css?ver=0.2` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/wp-emoji-release.min.js?ver=8aa70aa281d587c0748bf3090a76dc34` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/plugins/borlabs-cookie/assets/javascript/borlabs-cookie.min.js?ver=2.2.63` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/js/bzi-util.js?ver=1` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/plugins/twentytwenty/js/jquery.twentytwenty.js?ver=1` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/plugins/twentytwenty/js/jquery.event.move.js?ver=1` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/plugins/wp-show-more/wpsm-script.js?ver=1.0.1` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/plugins/cryptx/js/cryptx.min.js?ver=8aa70aa281d587c0748bf3090a76dc34` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/plugins/borlabs-cookie/assets/javascript/borlabs-cookie-prioritize.min.js?ver=2.2.63` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/js/bzi-map.js?ver=1` |
| +6 |  |  | industriekultur.berlin | 3 | get | script | `https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.5.1/gpx.min.js?ver=1.71` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/js/leaflet/plugins/leaflet-markercluster/leaflet.markercluster.js?ver=1.71` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/js/leaflet/plugins/leaflet-custom/Leaflet.Control.Custom.js?ver=1.71` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/js/leaflet/leaflet.js?ver=1.71` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.0` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/jquery/jquery.min.js?ver=3.6.4` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/dom-ready.min.js?ver=392bdd43726760d1f3ca` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/blocks.min.js?ver=639e14271099dc3d85bf` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/shortcode.min.js?ver=7539044b04e6bca57f2e` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/html-entities.min.js?ver=36a4a255da7dd2e1bf8e` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/data.min.js?ver=90cebfec01d1a3f0368e` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/redux-routine.min.js?ver=d86e7e9f062d7582f76b` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/private-apis.min.js?ver=6f247ed2bc3571743bba` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/compose.min.js?ver=7d5916e3b2ef0ea01400` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/priority-queue.min.js?ver=422e19e9d48b269c5219` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/keycodes.min.js?ver=184b321fa2d3bc7fd173` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/i18n.min.js?ver=9e794f35a71bb98672ae` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/is-shallow-equal.min.js?ver=20c2b06ecf04afb14fee` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/element.min.js?ver=b3bda690cfc516378771` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/escape-html.min.js?ver=03e27a7b6ae14f7afaa6` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/vendor/react-dom.min.js?ver=18.2.0` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/dom.min.js?ver=e03c89e1dd68aee1cb3a` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/deprecated.min.js?ver=6c963cb9494ba26b77eb` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/hooks.min.js?ver=4169d3cf8e8d95a3d6d5` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/vendor/react.min.js?ver=18.2.0` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/block-serialization-default-parser.min.js?ver=30ffd7e7e199f10b2a6d` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/blob.min.js?ver=e7b4ea96175a89b263e2` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/autop.min.js?ver=43197d709df445ccf849` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=3.15.0` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/vendor/regenerator-runtime.min.js?ver=0.13.11` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/vendor/wp-polyfill-inert.min.js?ver=3.1.2` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.19` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/cache/borlabs-cookie/borlabs-cookie_1_de.css?ver=2.2.63-43` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/plugins/twentytwenty/css/twentytwenty.css?ver=1` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/js/leaflet/plugins/leaflet-markercluster/markercluster-bzi.css?ver=1.71` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/js/leaflet/leaflet.css?ver=1.71` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/style.css?ver=0.2` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/plugins/wp-show-more/wpsm-style.css?ver=8aa70aa281d587c0748bf3090a76dc34` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/plugins/cryptx/css/cryptx.css?ver=8aa70aa281d587c0748bf3090a76dc34` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-includes/css/classic-themes.min.css?ver=8aa70aa281d587c0748bf3090a76dc34` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-column/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-two-columns/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-places-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-listing-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-map-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-color-block-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-timeline-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-appointments-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-route-block/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-routes-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-whitespace-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-talks-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-pastlist-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-contact-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-times-block/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-button/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-start-section-current/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-start-section-appointments/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-start-section-map/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-start-section/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-start-header/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-image-slider/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-header-slider/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-header-image/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-header-text/style.css?ver=1618138271` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-content/themes/bitgilde-bzi-theme/blocks/bzi-newsletter/style.css?ver=1617632628` |
| +6 |  |  | industriekultur.berlin | 1 | get | css | `https://industriekultur.berlin/wp-includes/css/dist/block-library/style.min.css?ver=8aa70aa281d587c0748bf3090a76dc34` |
| +6 |  |  | industriekultur.berlin | 1 | get | script | `https://industriekultur.berlin/wp-content/plugins/w3-total-cache/pub/js/lazyload.min.js` |
| +0 |  |  | industriekultur.berlin | 1 | get | doc | `https://industriekultur.berlin/` |
</details>

**Comment by spirillen** [comment]
This one as well `flechtner.de` only finds g pageads

<details><summary>Click to expand</summary>

```html
<HTML>
<HEAD>
<meta charset="utf-8">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7736695697017085"
     crossorigin="anonymous"></script><TITLE>
Willkommen auf www.flechtner.de
</TITLE>
<style type="text/css">
a:link { text-decoration:none; font-weight:bold; color:#000000; }
a:visited { text-decoration:none; font-weight:bold; color:#200000; }
a:hover { text-decoration:none; font-weight:bold; background-color:#ffCC33; }
a:active { text-decoration:none; font-weight:bold; background-color:#FFCC33; }
a:focus { text-decoration:none; font-weight:bold; background-color:#FFCC33; }
</style>
</HEAD>
<BODY>
<center>
<img src="verkehrsschild2.gif" width=800 height=522 usemap="#wegweiser" border=0>
<map name="wegweiser">
    <area shape="rect" coords="305,72,395,97"
          href="https://www.markusdba.de/" target="_blank" alt="oracle-blog" title="oracle-blog">
    <area shape="rect" coords="380,72,540,97"
          href="https://www.kanuslalom.de/" target="_blank" alt="kanuslalom" title="kanuslalom">
	<area shape="rect" coords="604,247,768,271"
          href="https://www.canoeslalom.net/" target="_blank" alt="ergebnisse - results" title="ergebnisse - results">
    <area shape="rect" coords="604,292,696,313"
          href="https://regeln.kanuslalom.de/" target="_blank" alt="regeln" title="regeln - rules">
    <area shape="rect" coords="66,292,128,313"
          href="text.html" target="_blank" alt="bilder" title="Text">
          </map>

<table>
<tr>
<TD align=left><H5>Canoe Slalom:
<BR>
Job &amp; Personal:
<BR>
Others:
<BR>
Contact &amp; Imprint:
</H5></TD>
<TD ALIGN=RIGHT><h5>
<a href="http:s//www.kanuslalom.de/" target="_blank">www.kanuslalom.de</A>
* <a href="https://regeln.kanuslalom.de/" target="_blank">regeln.kanuslalom.de</A>
* <a href="https://www.canoeslalom.net" target="_blank">www.canoeslalom.net</A>
* <a href="https://blog.canoeslalom.net" target="_blank">blog.canoeslalom.net</A>
* <a href="https://rl-tagebuch.kanuslalom.de" target="_blank">rl-tagebuch.kanuslalom.de</A>
<BR>
<a href="https://www.markusdba.de/" target="_blank">www.markusdba.de</A>
* <a href="https://www.markusdba.net/" target="_blank">www.markusdba.net</A>
<BR>
<a href="https://www.hgh88.de/" target="_blank">www.hgh88.de</A>
* <a href="https://www.radundinsel.de/" target="_blank">radundinsel.de - Reiseblog</A>
<BR>
<a href="impressum_datenschutz.html">Contact, Imprint & Data Protection - Impressum+Datenschutzerklärung</A></h5>
</TD>
</TR>
</TABLE>
</center>
</BODY>
<HTML>
```


</details>

**Comment by ShadowWhisperer** [comment]
Not sure where you are seeing these domains. I do not  have any of these, in any of the lists. 😕

**Comment by spirillen** [comment]
> Not sure where you are seeing these domains. I do not have any of these, in any of the lists. confused

Super, it is the bot who should have imported these from you

![image](https://github.com/ShadowWhisperer/BlockLists/assets/44526987/ba37d8ae-2179-4b66-97b3-884b7e164626)

but glad to know I'm not the only one who don't know why these should have been added.

Thanks for your reply
