### ISSUE TITLE
gambling

### ISSUE THREAD

**Issue by alsyundawy** [ShadowWhisperer/BlockLists#112]
as title , can you add to list too?

**Comment by ShadowWhisperer** [comment]
Years ago I had a gambling list. The issue now is, there are so many scam sites, it hard to keep track of the legit ones. Just parsing a index page is not enough, There are tons of Chinese sites that claim to be gambling sites (Specifically **1win** and slots. They are put up after a website's domain name is expired. (Often has nothing to do with the name)

I'll think about making a list of the top legal gambling sites. Right now, I just ignore them.

**Here are some other lists that contain gambling domains:**
```
https://raw.githubusercontent.com/blocklistproject/Lists/master/gambling.txt
https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts
```

**Comment by ShadowWhisperer** [comment]
I started a Gambling list.

Not as many domains yet, but all manually verified. Lists above contain a ton of dead/not gambling domains.
