### ISSUE TITLE
False Positives.

### ISSUE THREAD

**Issue by archon-valec** [ShadowWhisperer/BlockLists#113]
Think I found a couple false positives:

nessus.org - this is a well known and legit URL. Nessus is a vulnerability scanner provided by tenable.

backblazeb2.com - Backblaze is a very popular offsite backup service (might be variations on the URL also)

thoughts?

**Comment by ShadowWhisperer** [comment]
**nessus.org** - Removed, not sure why it was flagged.

**backblazeb2.com** - Removed. Was flagged as phishing links. I see it list on Backblaze's site as legit
[VirusTotal](https://www.virustotal.com/gui/domain/backblazeb2.com/community)

Thanks!

**Comment by archon-valec** [comment]
Hello, FYI still getting blocked when updating Nessus plugins. checked logs and this list is blocking "plugins.nessus.org" still. See attached log:

![image](https://github.com/ShadowWhisperer/BlockLists/assets/83673957/1f8b51a6-6c64-4e2b-95ea-db7325c3cb16)

**Comment by ShadowWhisperer** [comment]
Updated, thanks!
