### ISSUE TITLE
www.techtarget.com techtarget.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#115]
False positive I beleive ; this is a tech blog

**Comment by ShadowWhisperer** [comment]
Not a tech blog.

`TechTarget provides purchase intent-driven marketing and sales services for enterprise technology companies.`
[Source](https://www.crunchbase.com/organization/techtarget)

**Comment by p1r473** [comment]
Heres some examples: @ShadowWhisperer 
https://www.techtarget.com/searchmobilecomputing/tip/How-to-fix-an-iPhone-Personal-Hotspot-thats-not-working

They have a large amount of how-tos
![image](https://github.com/ShadowWhisperer/BlockLists/assets/9235633/86004d71-cbc6-4497-bf3b-1d9357134669)

**Comment by ShadowWhisperer** [comment]
The company primary does user tracking. Will remain blocked on my end.
Same type of article can be found elsewhere. Not worth giving tracking information from other sites.
