### ISSUE TITLE
prod.assets.mcxdiego.prime.amazon.dev

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#116]
This seems to have broken 'Manage Prime Membership' on Android Amazon App

**Comment by ShadowWhisperer** [comment]
Seems to be working

![1](https://github.com/ShadowWhisperer/BlockLists/assets/61057625/ad438678-0349-4c47-bf27-047f6109b680)

**Comment by p1r473** [comment]
Hmm I will retest

**Comment by p1r473** [comment]
Looks like it mightve been from a different list - assets.pixel.prime.amazon.dev
These domains are so hard to isolate and test sometimes - sorry!

**Comment by ShadowWhisperer** [comment]
No problem! That's why I double check, instead of just whitelisting.
