### ISSUE TITLE
geo.cardinalcommerce.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#117]
This seems to break ordering on bestbuy.ca, the "promo code" portion of the purchase page circles forever
![image](https://github.com/ShadowWhisperer/BlockLists/assets/9235633/081c2615-d705-4c9a-aadb-e29500fb9f5d)

**Comment by ShadowWhisperer** [comment]
Whitelisted. Thanks!

**Comment by p1r473** [comment]
Seem to be having the same issue with centinelapi.cardinalcommerce.com too @ShadowWhisperer 
Can you try to validate?
Looks like I needed to whitelist both of em

**Comment by ShadowWhisperer** [comment]
Yes, it is now whitelisted. Thanks!

*Looks like it processed here: https://centinelapi.cardinalcommerce.com/V1/Cruise/Collect
while looking up the original domain. Everything I do on my test machine is logged and scanned.
