### ISSUE TITLE
k.twitchcdn.net - Can't follow on twitch

### ISSUE THREAD

**Issue by myyystic** [ShadowWhisperer/BlockLists#118]
So, whenever i try to follow someone, it seems like it follow normally, but when i come back i notice it actually didn't. it took me a while to notice that and i lost track of few streamers. i was trying to track down what exactly was causing it, clearing cookies, disabling extensions/scripts, and some filters, and found out it's your ''tracking'' filterlist causing it. I don't know if it was intentional anyways, cause there's a shitload of filters to block amazon tracking on this filterlist, and i know twitch's not a very privacy friendly platform, but i'd like to keep using it for a while more for a lack of better alternative. So if it was intentional or not, i wanted to point it out. I enjoy ur filters very much. I'm using the majority of them with not other issues.

**Comment by ShadowWhisperer** [comment]
Looks like it is **"k.twitchcdn.net"**. It also breaks my login now. Whitelisted.
Thank you for bringing this to my attention!

**Comment by myyystic** [comment]
> Looks like it is **"k.twitchcdn.net"**. It also breaks my login. Whitelisted. Thank you for bringing this to my attention!

No more issues now indeed, thanks a ton ❤️
