### ISSUE TITLE
FirebaseCloudMessaging being broken

### ISSUE THREAD

**Issue by yoshimo** [ShadowWhisperer/BlockLists#119]
An App that wants to subscribe to the FirebaseCloudMessaging system for push notifications needs ```firebaseinstallations.googleapis.com``` in all or at least multiple cases according to `https://www.kuketz-blog.de/google-firebase-zwingend-erforderlich-fuer-den-empfang-von-push-nachrichten/`
This in itself doesn't constitute tracking or advertising.
I think you should remove it

**Comment by ShadowWhisperer** [comment]
It does classify as **Push Notifications**

**Comment by yoshimo** [comment]
It is infrastructure and can be used for good and bad.

**Comment by spirillen** [comment]
> It is infrastructure and can be used for good and bad.

Sorry, but only bad things.... it is google infrastructure for tracking **_YOU_**
