### ISSUE TITLE
Adult Sites

### ISSUE THREAD

**Issue by anxiouslelimo** [ShadowWhisperer/BlockLists#121]
aagmaal.cc
aagmaal.city
aagmaal.click
aagmaal.club
aagmaal.com
aagmaal.fun
aagmaal.gay
aagmaal.gives
aagmaal.icu
aagmaal.mba
aagmaal.mobi
aagmaal.mov
aagmaal.online
aagmaal.org
aagmaal.pics
aagmaal.pro
aagmaal.pw
aagmaal.run
aagmaal.sbs
aagmaal.site
aagmaal.skin
aagmaal.tattoo
aagmaal.tel
aagmaal.today
aagmaal.vip
aagmaal.work
aagmaal.xyz
aagmaals.com
aagmaals.me
aagmaals.net
aagmaaltube.com
ottmaza.expert

**Comment by ShadowWhisperer** [comment]
Added the list below. The remaining either redirect or were already blocked. Thanks!
```
aagmaal.cc
aagmaal.click
aagmaal.club
aagmaal.com
aagmaal.gay
aagmaal.icu
aagmaal.mba
aagmaal.mobi
aagmaal.pw
aagmaal.run
aagmaal.site
aagmaals.me
aagmaaltube.com
aagmaal.vip
ottmaza.expert
```
