### ISSUE TITLE
False positive Xiaomi domain

### ISSUE THREAD

**Issue by pepsiman-dev** [ShadowWhisperer/BlockLists#127]
Hi.

Xiaomi main site mi.com breaks with the added appmifile.com domain on the Malware list. Please, whitelisted it.

**Comment by ShadowWhisperer** [comment]
Hi,

I do not see that I have **appmifile.com** blocked, anywhere.
I do not see that it was every blocked under malware.

**Comment by pepsiman-dev** [comment]
Sorry, you're right! The correct domain is wsglb0.com (chinese CDN, I think), somehow related to appmifile.com. I just noticed from the logs of my AdGuard DNS service.

![Screenshot from 2023-10-20 11-47-56](https://github.com/ShadowWhisperer/BlockLists/assets/86396338/7df5d8ba-281c-4a41-8ffd-c8637ba1f611)

**Comment by ShadowWhisperer** [comment]
Whitelisted. Thanks!

```
/home/x > dig i01.appmifile.com

; <<>> DiG 9.11.5-P4-5.1+deb10u8-Debian <<>> i01.appmifile.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13527
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;i01.appmifile.com.		IN	A

;; ANSWER SECTION:
i01.appmifile.com.	49	IN	CNAME	i01.appmifile.com.mgslb.com.
i01.appmifile.com.mgslb.com. 49	IN	CNAME	i01.appmifile.com.wsglb0.com.
i01.appmifile.com.wsglb0.com. 49 IN	A	157.185.179.12

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Oct 20 11:18:44 CDT 2023
;; MSG SIZE  rcvd: 145
```
