### ISSUE TITLE
Remove Beeceptor

### ISSUE THREAD

**Issue by ankitjaininfo** [ShadowWhisperer/BlockLists#129]
This is a request for the removal for Beeceptor. [Beeceptor.com](https://beeceptor.com/) domain is listed in the file https://github.com/ShadowWhisperer/BlockLists/blob/master/RAW/Risk 

Beeceptor is an API mocking and HTTP debugging tool, and a SaaS product. It's popular and shouldn't be added to blocklists.

**Comment by ShadowWhisperer** [comment]
Beeceptor can be used as a webhook.  
I have seen webhooks abused, which is why I block them, under _Risk_.  

`Webhook  =  Inspect page requests  (Can be used to receive data from an infected system)`

**Comment by ankitjaininfo** [comment]
Hi @ShadowWhisperer ,

Beeceptor is a developer tool. There are other tools like [Webhook.site](https://Webhook.site), [ReqBin](https://public.requestbin.com/r), ngrok, Postman can also be used as webhooks.

I insist to consider Beeceptor under good books and removing it from this listing.

**Comment by ShadowWhisperer** [comment]
Webhooks will remain blocked under _Risk_. Purpose of _Risk_ is to prevent potential problems, and give an alert (on my setup). These lists are used in a repair center (where malware is involved on a day to day basis), and anything that could potentially cause problems, I want blocked.

The webhooks already in _Risk_, are ones I've seen (good and bad), not gathered from lists. I haven't gone out my way looking for them, atm.

Suggestion: Whitelist internally
