### ISSUE TITLE
0xacab.org

### ISSUE THREAD

**Issue by iam-py-test** [ShadowWhisperer/BlockLists#130]
`0xacab.org` is listed in https://github.com/ShadowWhisperer/BlockLists/blob/master/RAW/Risk
However, it is just a GitLab instance.
Thanks

**Comment by ShadowWhisperer** [comment]
I wasn't aware it was part of GitLab. Looked shady.  
Whitelisted. Thanks!

**Comment by iam-py-test** [comment]
It isn't part of GitLab or owned by GitLab. It's just a GitLab instance used by a few projects I have contributed to.
Thanks
