### ISSUE TITLE
Malware list blocks digital-delivery.com

### ISSUE THREAD

**Issue by timkgh** [ShadowWhisperer/BlockLists#133]
https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Malware#L8002

`notifications.digital-delivery.com` is a legit domain used by T-Mobile to send bills via email.

I see that it may have been used for malicious purposes in the past, so it's a tough call what to do with it.

It's used by other legit services also, for billing purposes.
https://www.reddit.com/r/Scams/comments/ycgrk7/i_cant_tell_if_this_is_fake_or_just_quest/

**Comment by ShadowWhisperer** [comment]
Looks like they no longer hide their registration information. Whitelisted.  

[Broadridge Financial Solutions, Inc.](https://www.broadridge.com/)  
  
[Wiki](https://en.wikipedia.org/wiki/Broadridge_Financial_Solutions)  

Additional:
`https://forums.malwarebytes.com/topic/313997-digital-deliverycom-on-your-blog-as-associated-with-a-trojan/`
