### ISSUE TITLE
Malware list adform.dk

### ISSUE THREAD

**Issue by joe820912boy** [ShadowWhisperer/BlockLists#134]
https://github.com/ShadowWhisperer/BlockLists/blob/master/RAW/Malware#L2200

adform.dk should be used for advertisement provider Adform seems not be a malware domain 

And check by using adguard and virustotal

https://reports.adguard.com/zh_tw/adform.dk/report.html
https://www.virustotal.com/gui/url/874976b393936622092b95a0b3bf374393b6e026b01784c707783056cb6364eb

**Comment by spirillen** [comment]
Not sure it even worth that... seems like it redirects to its mother by default

```bash
curl -I adform.dk
HTTP/1.1 301 Moved Permanently
Date: Tue, 23 Jan 2024 04:07:08 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Tue, 23 Jan 2024 05:07:08 GMT
Location: https://site.adform.com/
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=AojktQ%2Bp%2Fvy%2BGaSza9qKOf72W%2BDyVH6A0wqnx2Cf4qcJ5pk2VqjAkuKbaZibrPzThQwTAysJGlft%2B6vx%2F3wR15r8MUNwRd1ZPpIJKPIgX7D%2BlN71NYNSnapaqR8%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 849d2b0798d0abe1-CPH
alt-svc: h3=":443"; ma=86400
```

**Comment by joe820912boy** [comment]
Yes, I check it will auto redirect to adform.com

So not very sure about it should be classfied to AD or Malware
