### ISSUE TITLE
sexy-dating.app.link in Malware list

### ISSUE THREAD

**Issue by joe820912boy** [ShadowWhisperer/BlockLists#135]
[in list](https://github.com/ShadowWhisperer/BlockLists/blob/master/RAW/Malware#L27687)

This domain should be more likely classifed by adult category, not in malware list

Some references,
https://reports.adguard.com/zh_tw/sexy-dating.app.link/report.html
https://www.virustotal.com/gui/url/eea5566da7860c75f2e7aab926cff5805c1e1b323dd74cda0e02347882735a55
https://transparencyreport.google.com/safe-browsing/search?url=sexy-dating.app.link&hl=en

**Comment by ShadowWhisperer** [comment]
Looks like it is a **re-director**. 

Going to link directly, redirects to: `sugarbabyroom.com` (Does not resolv) [VirusTotal](https://www.virustotal.com/gui/domain/sugarbabyroom.com)

Found this link in google: `https://sexy-dating.app.link/cKyFTVHslhb?utm_medium=social&utm_source=heylink.me`
Link redirects to `vzknmq.facebookdates.net`, which is now **parked**, and shown as **malicious** in [VirusTotal](https://www.virustotal.com/gui/domain/facebookdates.net)

**Comment by joe820912boy** [comment]
OK, I got it. 

And want to know that how to found https://sexy-dating.app.link/cKyFTVHslhb?utm_medium=social&utm_source=heylink.me in google? 

So that maybe next time I will check it again before I post the issue

**Comment by ShadowWhisperer** [comment]
Google search for `"sexy-dating.app.link"` with the quotes.

Control + F = Find `sexy-dating.app.link/` with the slash

![Capture](https://github.com/ShadowWhisperer/BlockLists/assets/61057625/471ff3b8-d4d5-4ab0-98f7-4a0150344425)
