### ISSUE TITLE
False Positive - drivereasy.com, driveridentifier.com, driverscape.com, driverpack.io

### ISSUE THREAD

**Issue by Marcus1Pierce** [ShadowWhisperer/BlockLists#136]
drivereasy.com, driveridentifier.com, driverscape.com, driverpack.io is a website that provides drivers. I don’t think it is a malware. I often use some of those websites to find specific drivers for my device and so far I have never received any malware notification from my antivirus from what I downloaded from those websites. The only thing is that there might be some bloatware during the software installation.

https://github.com/ShadowWhisperer/BlockLists/blob/9880625508a69e9e0f36e3e8890ef76ff880ab72/Lists/Malware#L9525
https://github.com/ShadowWhisperer/BlockLists/blob/9880625508a69e9e0f36e3e8890ef76ff880ab72/Lists/Malware#L9535
https://github.com/ShadowWhisperer/BlockLists/blob/9880625508a69e9e0f36e3e8890ef76ff880ab72/Lists/Malware#L9539
https://github.com/ShadowWhisperer/BlockLists/blob/9880625508a69e9e0f36e3e8890ef76ff880ab72/Lists/Malware#L9543

**Comment by iam-py-test** [comment]
I can not speak for the others, but DriverEasy is a Potentially Unwanted Program (malware) and ["snake oil"](https://www.malwarebytes.com/blog/news/2015/06/driver-updaters-digital-snake-oil-part-2).
In general, the only way you should get drivers is through Windows Update or from your manufacturer; experts strongly recommend against using third parties.
Thanks
