### ISSUE TITLE
List of suggestions for sources of hosts data Gambling (Indonesia)

### ISSUE THREAD

**Issue by alsyundawy** [ShadowWhisperer/BlockLists#138]
List of suggestions for sources of hosts data Gambling (Indonesia)

https://raw.githubusercontent.com/alsyundawy/TrustPositif/main/judi-Sep23_20Feb2024.txt

**Comment by ShadowWhisperer** [comment]
Thanks! I'll check em out.

**Comment by alsyundawy** [comment]
i am engineer internet service provider from indonesia

indonesia have rules to bloking porn, scamming, copyright & gambling from indonesia Ministry of Communication and Informatics (Kementerian Komunikasi dan Informatika Republik Indonesia) kominfo.go.id. this list not for publik but for internet service provider only. they send daily list to all ISP via email, then make compilation then for you just gambling site online

https://prnt.sc/1BDFIiDzZKhC

https://prnt.sc/URdIgYVh1Z5x

you can check list https://trustpositif.kominfo.go.id/

https://prnt.sc/IOTww_OEit_b

**Comment by ShadowWhisperer** [comment]
Very cool! I'll definitely use this as a resource. I want to verify before combining it.
Just doing a quick check (After seeing many "Your country is blocked"), I see a false positive. **4for4.com** Site does has articles on betting, but does not take bets.

![Capture](https://github.com/ShadowWhisperer/BlockLists/assets/61057625/c2021ffe-0589-4b20-b972-886d01d829d7)

**Comment by alsyundawy** [comment]
Thx for response

my plan I will try to update a maximum of once every 2-3 days, currently only using the list September 2023 - 20 February 2024. Meanwhile, I will update the database before or after. using new name dinamic database

https://raw.githubusercontent.com/alsyundawy/TrustPositif/main/gambling_indonesia.txt

**Comment by hagezi** [comment]
@ShadowWhisperer 

Result of my quick analysis:

https://github.com/hagezi/dns-blocklists/issues/2207#issuecomment-1956658136

https://github.com/hagezi/dns-blocklists/issues/2207#issuecomment-1957461777

**Comment by spirillen** [comment]
@alsyundawy I've just stumbled on `110100101011010101l001.shop` from your gist which seems dead

I like your idea of sharing the list. If you like I can help building you a repo that removes FS's and other dead domain by using @PyFunceble.

**Comment by alsyundawy** [comment]
arrg we cant check becouse all list from dump goverment -_-

**Comment by alsyundawy** [comment]
switched source to https://raw.githubusercontent.com/alsyundawy/TrustPositif/main/gambling_indonesia.txt

update now with latest db

**Comment by spirillen** [comment]
`110100101011010101l001.shop` is still on the new list...

```python
pyfunceble -a -d 110100101011010101l001.shop

██████╗ ██╗   ██╗███████╗██╗   ██╗███╗   ██╗ ██████╗███████╗██████╗ ██╗     ███████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██║   ██║████╗  ██║██╔════╝██╔════╝██╔══██╗██║     ██╔════╝
██████╔╝ ╚████╔╝ █████╗  ██║   ██║██╔██╗ ██║██║     █████╗  ██████╔╝██║     █████╗
██╔═══╝   ╚██╔╝  ██╔══╝  ██║   ██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗██║     ██╔══╝
██║        ██║   ██║     ╚██████╔╝██║ ╚████║╚██████╗███████╗██████╔╝███████╗███████╗
╚═╝        ╚═╝   ╚═╝      ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═════╝ ╚══════╝╚══════╝



Subject                                                                                              Status      Source
---------------------------------------------------------------------------------------------------- ----------- ----------
110100101011010101l001.shop                                                                          INACTIVE    STDLOOKUP

Execution Time: 00:00:00:6.388985
```

**Comment by alsyundawy** [comment]
Update 02042024

**Comment by ShadowWhisperer** [comment]
I wondered why there were so many

https://cside.dev/blog/over-150k-websites-hit-by-full-page-hijack-linking-to-chinese-gambling-sites

**Comment by spirillen** [comment]
> I wondered why there were so many
> 
> https://cside.dev/blog/over-150k-websites-hit-by-full-page-hijack-linking-to-chinese-gambling-sites

Not bad, wonder how much they get paid br the brokers when they read this article...

@g0d33p3rsec , this is an article for you 📰

**Comment by alsyundawy** [comment]
thx noted
