### ISSUE TITLE
False Positive - onelogin.wpcdn.pl

### ISSUE THREAD

**Issue by sefinek24** [ShadowWhisperer/BlockLists#139]
https://github.com/ShadowWhisperer/BlockLists/blob/5935e0416a19cd7e8145fb23fdec4d68cb0eefe2/Lists/Ads#L12623

It's simply a CDN for a certain Polish [email service](https://www.wp.pl).

**Comment by ShadowWhisperer** [comment]
Whitelisted. Thanks!
It will be removed in the next update.
