### ISSUE TITLE
Fundraiseup

### ISSUE THREAD

**Issue by yoshimo** [ShadowWhisperer/BlockLists#140]
It is used by Thunderbird to collect donations.
I would make this a bit more specific

```
 fundraiseup.com
``` 

should turn into
```
sentry.fundraiseup.com
```
This way, the donation box would still appear on ```https://www.thunderbird.net/en-US/donate/#donate```

**Comment by ShadowWhisperer** [comment]
I'm thinking the whole domain is blocked, due to Thunderbird opening a donation page after installation.

If that is the case, it will be moved to **bloat**.  


Whitelisted  
```cdn.fundraiseup.com
static.fundraiseup.com
fundraiseup.com```


Thanks!
