### ISSUE TITLE
False Positive - go.nordvpn.net

### ISSUE THREAD

**Issue by Ryckie** [ShadowWhisperer/BlockLists#141]
I noticed that go.nordvpn.net is blocked via CNAME of IP with your ShadowWhisperer's Malware List.
I believe this is not correct.

`||go2cloud.org^`

**Comment by ShadowWhisperer** [comment]
Hi.

I noticed this last night for some other domains. It will be whitelisted in the next update.

Originally blocked: `https://www.malwarebytes.com/blog/detections/go2cloud-org`

Thanks!
