### ISSUE TITLE
Extra Spotlight Suggestions

### ISSUE THREAD

**Issue by WoefulWrecker** [ShadowWhisperer/BlockLists#142]
[BlockLists](https://github.com/ShadowWhisperer/BlockLists/tree/master)/[Lists](https://github.com/ShadowWhisperer/BlockLists/tree/master/Lists)
/Apple:

Something to think about

 # Spotlight Suggestions

api-aapne1a.smoot.apple.com
api-aapne1c.smoot.apple.com
api-aaps1b.smoot.apple.com
api-aapse1b.smoot.apple.com
api-aapse1c.smoot.apple.com
api-aapse2c.smoot.apple.com
api-aeuc1a.smoot.apple.com
api-aeuc1b.smoot.apple.com
api-aeuw1b.smoot.apple.com
api-aeuw3b.smoot.apple.com
api-aeuw3c.smoot.apple.com
api-ams.smoot.apple.com
api-apps-ci.smoot.apple.com
api-apps-stg.smoot.apple.com
api-apps.smoot.apple.com
api-asae1b.smoot.apple.com
api-ause1a.smoot.apple.com
api-ause1b.smoot.apple.com
api-ause1c.smoot.apple.com
api-ause2a.smoot.apple.com
api-ause2b.smoot.apple.com
api-ause2c.smoot.apple.com
api-ausw2b.smoot.apple.com
api-ausw2c.smoot.apple.com
api-carry-mes.smoot.apple.com
api-carry.smoot.apple.com
api-che.smoot.apple.com
api-ci-ausw2c-e.smoot.apple.com
api-ci-ausw2c.smoot.apple.com
api-ci-mes.smoot.apple.com
api-ci.smoot.apple.com
api-concat-mes.smoot.apple.com
api-debug-mes.smoot.apple.com
api-demo-mes.smoot.apple.com
api-dub.smoot.apple.com
api-finance-ci.smoot.apple.com
api-finance-stg.smoot.apple.com
api-finance.smoot.apple.com
api-fra.smoot.apple.com
api-glb-aapne1a.smoot.apple.com
api-glb-aapne1c.smoot.apple.com
api-glb-aaps1b.smoot.apple.com
api-glb-aapse1c.smoot.apple.com
api-glb-aapse2c.smoot.apple.com
api-glb-abt.smoot.apple.com
api-glb-aeuc1a.smoot.apple.com
api-glb-aeuc1b.smoot.apple.com
api-glb-aeuw1b.smoot.apple.com
api-glb-aeuw3b.smoot.apple.com
api-glb-aeuw3c.smoot.apple.com
api-glb-asae1b.smoot.apple.com
api-glb-ause1a.smoot.apple.com
api-glb-ause1b.smoot.apple.com
api-glb-ause1c.smoot.apple.com
api-glb-ause2a.smoot.apple.com
api-glb-ause2b.smoot.apple.com
api-glb-ause2c.smoot.apple.com
api-glb-ausw2b.smoot.apple.com
api-glb-ausw2c.smoot.apple.com
api-glb-sjcdm1.smoot.apple.com
api-img-ci.smoot.apple.com
api-img-stg.smoot.apple.com
api-img.smoot.apple.com
api-jnb.smoot.apple.com
api-lookup-aapne1a.smoot.apple.com
api-lookup-aapne1c.smoot.apple.com
api-lookup-aaps1b.smoot.apple.com
api-lookup-aapse1c.smoot.apple.com
api-lookup-aapse2c.smoot.apple.com
api-lookup-aeuc1a.smoot.apple.com
api-lookup-aeuc1b.smoot.apple.com
api-lookup-aeuw1b.smoot.apple.com
api-lookup-aeuw3b.smoot.apple.com
api-lookup-aeuw3c.smoot.apple.com
api-lookup-asae1b.smoot.apple.com
api-lookup-ause1a.smoot.apple.com
api-lookup-ause1b.smoot.apple.com
api-lookup-ause1c.smoot.apple.com
api-lookup-ause2a.smoot.apple.com
api-lookup-ause2b.smoot.apple.com
api-lookup-ause2c.smoot.apple.com
api-lookup-ausw2b.smoot.apple.com
api-lookup-ausw2c.smoot.apple.com
api-lookup-ci.smoot.apple.com
api-lookup-stg.smoot.apple.com
api-lookup.smoot.apple.com
api-mes.smoot.apple.com
api-mum.smoot.apple.com
api-music-ci.smoot.apple.com
api-music-data-match.smoot.apple.com
api-music-stg.smoot.apple.com
api-music.smoot.apple.com
api-news-ci.smoot.apple.com
api-news-mes.smoot.apple.com
api-news-stg.smoot.apple.com
api-news.smoot.apple.com
api-osa.smoot.apple.com
api-p-ap-a.smoot.apple.com
api-p-ap-b.smoot.apple.com
api-p-ap-c.smoot.apple.com
api-p-ap-d.smoot.apple.com
api-p-ap-e.smoot.apple.com
api-p-ap-f.smoot.apple.com
api-p-ap-g.smoot.apple.com
api-p-ap-h.smoot.apple.com
api-p-ap-i.smoot.apple.com
api-p-ap-j.smoot.apple.com
api-p-ap-k.smoot.apple.com
api-p-ap-l.smoot.apple.com
api-p-ap-m.smoot.apple.com
api-p-ap-n.smoot.apple.com
api-p-ap-o.smoot.apple.com
api-p-ap-p.smoot.apple.com
api-p-ap-q.smoot.apple.com
api-p-ap-r.smoot.apple.com
api-p-ap-s.smoot.apple.com
api-p-ap-t.smoot.apple.com
api-p-apac.smoot.apple.com
api-par.smoot.apple.com
api-podcast-ci.smoot.apple.com
api-podcast-stg.smoot.apple.com
api-podcast.smoot.apple.com
api-rno.smoot.apple.com
api-safari-ci.smoot.apple.com
api-safari-stg.smoot.apple.com
api-safari.smoot.apple.com
api-sba-ci.smoot.apple.com
api-sba-stg.smoot.apple.com
api-sba.smoot.apple.com
api-sel.smoot.apple.com
api-siri-aapne1a.smoot.apple.com
api-siri-aapne1c.smoot.apple.com
api-siri-aaps1b.smoot.apple.com
api-siri-aapse1c.smoot.apple.com
api-siri-aapse2c.smoot.apple.com
api-siri-aeuc1a.smoot.apple.com
api-siri-aeuc1b.smoot.apple.com
api-siri-aeuw1b.smoot.apple.com
api-siri-aeuw3b.smoot.apple.com
api-siri-aeuw3c.smoot.apple.com
api-siri-asae1b.smoot.apple.com
api-siri-ause1a.smoot.apple.com
api-siri-ause1b.smoot.apple.com
api-siri-ause1c.smoot.apple.com
api-siri-ause2a.smoot.apple.com
api-siri-ause2b.smoot.apple.com
api-siri-ause2c.smoot.apple.com
api-siri-ausw2b.smoot.apple.com
api-siri-ausw2c.smoot.apple.com
api-siri-ci.smoot.apple.com
api-siri-stg.smoot.apple.com
api-siri.smoot.apple.com
api-sports-ci.smoot.apple.com
api-sports-stg.smoot.apple.com
api-sports.smoot.apple.com
api-stg-ausw2b-e.smoot.apple.com
api-stg-ausw2b-ed.smoot.apple.com
api-stg-ausw2b.smoot.apple.com
api-stg-usw2b.smoot.apple.com
api-stg.smoot.apple.com
api-test-mes.smoot.apple.com
api-tpe.smoot.apple.com
api-video-ci.smoot.apple.com
api-video-stg.smoot.apple.com
api-video.smoot.apple.com
api.smoot.apple.com
api2.smoot.apple.com
carry-falcon-ausw2b.smoot.apple.com
carry-falcon.smoot.apple.com
cdn.smoot.apple.com
cdn2.smoot.apple.com
falcon-ausw2b.smoot.apple.com
falcon.smoot.apple.com
fbs-apse1.smoot.apple.com
fbs-ci.smoot.apple.com
fbs-euw1.smoot.apple.com
fbs-stg.smoot.apple.com
fbs-usw2.smoot.apple.com
fbs.smoot.apple.com
gr-aape1a.smoot.apple.com
gr-aape1b.smoot.apple.com
gr-aapne1a.smoot.apple.com
gr-aapne1c.smoot.apple.com
gr-aapne2a.smoot.apple.com
gr-aapne2b.smoot.apple.com
gr-aaps1a.smoot.apple.com
gr-aaps1b.smoot.apple.com
gr-aapse1a.smoot.apple.com
gr-aapse1b.smoot.apple.com
gr-aapse2a.smoot.apple.com
gr-aapse2b.smoot.apple.com
gr-aeun1a.smoot.apple.com
gr-aeun1b.smoot.apple.com
gr-aeus1b.smoot.apple.com
gr-aeus1c.smoot.apple.com
gr-aeuw1a.smoot.apple.com
gr-aeuw1b.smoot.apple.com
gr-api-apps-aape1a.smoot.apple.com
gr-api-apps-aape1b.smoot.apple.com
gr-api-apps-aapne1a.smoot.apple.com
gr-api-apps-aapne1c.smoot.apple.com
gr-api-apps-aapne2a.smoot.apple.com
gr-api-apps-aapne2b.smoot.apple.com
gr-api-apps-aaps1a.smoot.apple.com
gr-api-apps-aaps1b.smoot.apple.com
gr-api-apps-aapse1a.smoot.apple.com
gr-api-apps-aapse1b.smoot.apple.com
gr-api-apps-aapse2a.smoot.apple.com
gr-api-apps-aapse2b.smoot.apple.com
gr-api-apps-aeun1a.smoot.apple.com
gr-api-apps-aeun1b.smoot.apple.com
gr-api-apps-aeus1b.smoot.apple.com
gr-api-apps-aeus1c.smoot.apple.com
gr-api-apps-aeuw1a.smoot.apple.com
gr-api-apps-aeuw1b.smoot.apple.com
gr-api-apps-asae1a.smoot.apple.com
gr-api-apps-asae1b.smoot.apple.com
gr-api-apps-ause1b.smoot.apple.com
gr-api-apps-ause1c.smoot.apple.com
gr-api-apps-ause2a.smoot.apple.com
gr-api-apps-ause2b.smoot.apple.com
gr-api-apps-ausw2a.smoot.apple.com
gr-api-apps-ausw2b.smoot.apple.com
gr-api-apps-h-aape1a.smoot.apple.com
gr-api-apps-h-aape1b.smoot.apple.com
gr-api-apps-h-aapne1a.smoot.apple.com
gr-api-apps-h-aapne1c.smoot.apple.com
gr-api-apps-h-aapne2a.smoot.apple.com
gr-api-apps-h-aapne2b.smoot.apple.com
gr-api-apps-h-aaps1a.smoot.apple.com
gr-api-apps-h-aaps1b.smoot.apple.com
gr-api-apps-h-aapse1a.smoot.apple.com
gr-api-apps-h-aapse1b.smoot.apple.com
gr-api-apps-h-aapse2a.smoot.apple.com
gr-api-apps-h-aapse2b.smoot.apple.com
gr-api-apps-h-aeun1a.smoot.apple.com
gr-api-apps-h-aeun1b.smoot.apple.com
gr-api-apps-h-aeus1b.smoot.apple.com
gr-api-apps-h-aeus1c.smoot.apple.com
gr-api-apps-h-aeuw1a.smoot.apple.com
gr-api-apps-h-aeuw1b.smoot.apple.com
gr-api-apps-h-asae1a.smoot.apple.com
gr-api-apps-h-asae1b.smoot.apple.com
gr-api-apps-h-ause1b.smoot.apple.com
gr-api-apps-h-ause1c.smoot.apple.com
gr-api-apps-h-ause2a.smoot.apple.com
gr-api-apps-h-ause2b.smoot.apple.com
gr-api-apps-h-ausw2a.smoot.apple.com
gr-api-apps-h-ausw2b.smoot.apple.com
gr-api-apps-h.smoot.apple.com
gr-api-apps.smoot.apple.com
gr-api-ci-ausw2a.smoot.apple.com
gr-api-music-aape1a.smoot.apple.com
gr-api-music-aape1b.smoot.apple.com
gr-api-music-aapne1a.smoot.apple.com
gr-api-music-aapne1c.smoot.apple.com
gr-api-music-aapne2a.smoot.apple.com
gr-api-music-aapne2b.smoot.apple.com
gr-api-music-aaps1a.smoot.apple.com
gr-api-music-aaps1b.smoot.apple.com
gr-api-music-aapse1a.smoot.apple.com
gr-api-music-aapse1b.smoot.apple.com
gr-api-music-aapse2a.smoot.apple.com
gr-api-music-aapse2b.smoot.apple.com
gr-api-music-aeun1a.smoot.apple.com
gr-api-music-aeun1b.smoot.apple.com
gr-api-music-aeus1b.smoot.apple.com
gr-api-music-aeus1c.smoot.apple.com
gr-api-music-aeuw1a.smoot.apple.com
gr-api-music-aeuw1b.smoot.apple.com
gr-api-music-asae1a.smoot.apple.com
gr-api-music-asae1b.smoot.apple.com
gr-api-music-ause1b.smoot.apple.com
gr-api-music-ause1c.smoot.apple.com
gr-api-music-ause2a.smoot.apple.com
gr-api-music-ause2b.smoot.apple.com
gr-api-music-ausw2a.smoot.apple.com
gr-api-music-ausw2b.smoot.apple.com
gr-api-music-h-aape1a.smoot.apple.com
gr-api-music-h-aape1b.smoot.apple.com
gr-api-music-h-aapne1a.smoot.apple.com
gr-api-music-h-aapne1c.smoot.apple.com
gr-api-music-h-aapne2a.smoot.apple.com
gr-api-music-h-aapne2b.smoot.apple.com
gr-api-music-h-aaps1a.smoot.apple.com
gr-api-music-h-aaps1b.smoot.apple.com
gr-api-music-h-aapse1a.smoot.apple.com
gr-api-music-h-aapse1b.smoot.apple.com
gr-api-music-h-aapse2a.smoot.apple.com
gr-api-music-h-aapse2b.smoot.apple.com
gr-api-music-h-aeun1a.smoot.apple.com
gr-api-music-h-aeun1b.smoot.apple.com
gr-api-music-h-aeus1b.smoot.apple.com
gr-api-music-h-aeus1c.smoot.apple.com
gr-api-music-h-aeuw1a.smoot.apple.com
gr-api-music-h-aeuw1b.smoot.apple.com
gr-api-music-h-asae1a.smoot.apple.com
gr-api-music-h-asae1b.smoot.apple.com
gr-api-music-h-ause1b.smoot.apple.com
gr-api-music-h-ause1c.smoot.apple.com
gr-api-music-h-ause2a.smoot.apple.com
gr-api-music-h-ause2b.smoot.apple.com
gr-api-music-h-ausw2a.smoot.apple.com
gr-api-music-h-ausw2b.smoot.apple.com
gr-api-music-h.smoot.apple.com
gr-api-music.smoot.apple.com
gr-api-podcast-aape1a.smoot.apple.com
gr-api-podcast-aape1b.smoot.apple.com
gr-api-podcast-aapne1a.smoot.apple.com
gr-api-podcast-aapne1c.smoot.apple.com
gr-api-podcast-aapne2a.smoot.apple.com
gr-api-podcast-aapne2b.smoot.apple.com
gr-api-podcast-aaps1a.smoot.apple.com
gr-api-podcast-aaps1b.smoot.apple.com
gr-api-podcast-aapse1a.smoot.apple.com
gr-api-podcast-aapse1b.smoot.apple.com
gr-api-podcast-aapse2a.smoot.apple.com
gr-api-podcast-aapse2b.smoot.apple.com
gr-api-podcast-aeun1a.smoot.apple.com
gr-api-podcast-aeun1b.smoot.apple.com
gr-api-podcast-aeus1b.smoot.apple.com
gr-api-podcast-aeus1c.smoot.apple.com
gr-api-podcast-aeuw1a.smoot.apple.com
gr-api-podcast-aeuw1b.smoot.apple.com
gr-api-podcast-asae1a.smoot.apple.com
gr-api-podcast-asae1b.smoot.apple.com
gr-api-podcast-ause1b.smoot.apple.com
gr-api-podcast-ause1c.smoot.apple.com
gr-api-podcast-ause2a.smoot.apple.com
gr-api-podcast-ause2b.smoot.apple.com
gr-api-podcast-ausw2a.smoot.apple.com
gr-api-podcast-ausw2b.smoot.apple.com
gr-api-podcast.smoot.apple.com
gr-api-sba-ause1b.smoot.apple.com
gr-api-sba-ause1c.smoot.apple.com
gr-api-sba-ause2a.smoot.apple.com
gr-api-sba-ause2b.smoot.apple.com
gr-api-sba-ausw2a.smoot.apple.com
gr-api-sba-ausw2b.smoot.apple.com
gr-api-sba.smoot.apple.com
gr-api-siri-aape1a.smoot.apple.com
gr-api-siri-aape1b.smoot.apple.com
gr-api-siri-aapne1a.smoot.apple.com
gr-api-siri-aapne1c.smoot.apple.com
gr-api-siri-aapne2a.smoot.apple.com
gr-api-siri-aapne2b.smoot.apple.com
gr-api-siri-aaps1a.smoot.apple.com
gr-api-siri-aaps1b.smoot.apple.com
gr-api-siri-aapse1a.smoot.apple.com
gr-api-siri-aapse1b.smoot.apple.com
gr-api-siri-aapse2a.smoot.apple.com
gr-api-siri-aapse2b.smoot.apple.com
gr-api-siri-aeun1a.smoot.apple.com
gr-api-siri-aeun1b.smoot.apple.com
gr-api-siri-aeus1b.smoot.apple.com
gr-api-siri-aeus1c.smoot.apple.com
gr-api-siri-aeuw1a.smoot.apple.com
gr-api-siri-aeuw1b.smoot.apple.com
gr-api-siri-asae1a.smoot.apple.com
gr-api-siri-asae1b.smoot.apple.com
gr-api-siri-ause1b.smoot.apple.com
gr-api-siri-ause1c.smoot.apple.com
gr-api-siri-ause2a.smoot.apple.com
gr-api-siri-ause2b.smoot.apple.com
gr-api-siri-ausw2a.smoot.apple.com
gr-api-siri-ausw2b.smoot.apple.com
gr-api-siri-ci-ausw2a.smoot.apple.com
gr-api-siri-ci.smoot.apple.com
gr-api-siri.smoot.apple.com
gr-api-sports-aape1a.smoot.apple.com
gr-api-sports-aape1b.smoot.apple.com
gr-api-sports-aapne1a.smoot.apple.com
gr-api-sports-aapne1c.smoot.apple.com
gr-api-sports-aapne2a.smoot.apple.com
gr-api-sports-aapne2b.smoot.apple.com
gr-api-sports-aaps1a.smoot.apple.com
gr-api-sports-aaps1b.smoot.apple.com
gr-api-sports-aapse1a.smoot.apple.com
gr-api-sports-aapse1b.smoot.apple.com
gr-api-sports-aapse2a.smoot.apple.com
gr-api-sports-aapse2b.smoot.apple.com
gr-api-sports-aeun1a.smoot.apple.com
gr-api-sports-aeun1b.smoot.apple.com
gr-api-sports-aeus1b.smoot.apple.com
gr-api-sports-aeus1c.smoot.apple.com
gr-api-sports-aeuw1a.smoot.apple.com
gr-api-sports-aeuw1b.smoot.apple.com
gr-api-sports-asae1a.smoot.apple.com
gr-api-sports-asae1b.smoot.apple.com
gr-api-sports-ause1b.smoot.apple.com
gr-api-sports-ause1c.smoot.apple.com
gr-api-sports-ause2a.smoot.apple.com
gr-api-sports-ause2b.smoot.apple.com
gr-api-sports-ausw2a.smoot.apple.com
gr-api-sports-ausw2b.smoot.apple.com
gr-api-sports.smoot.apple.com
gr-api-video-aape1a.smoot.apple.com
gr-api-video-aape1b.smoot.apple.com
gr-api-video-aapne1a.smoot.apple.com
gr-api-video-aapne1c.smoot.apple.com
gr-api-video-aapne2a.smoot.apple.com
gr-api-video-aapne2b.smoot.apple.com
gr-api-video-aaps1a.smoot.apple.com
gr-api-video-aaps1b.smoot.apple.com
gr-api-video-aapse1a.smoot.apple.com
gr-api-video-aapse1b.smoot.apple.com
gr-api-video-aapse2a.smoot.apple.com
gr-api-video-aapse2b.smoot.apple.com
gr-api-video-aeun1a.smoot.apple.com
gr-api-video-aeun1b.smoot.apple.com
gr-api-video-aeus1b.smoot.apple.com
gr-api-video-aeus1c.smoot.apple.com
gr-api-video-aeuw1a.smoot.apple.com
gr-api-video-aeuw1b.smoot.apple.com
gr-api-video-asae1a.smoot.apple.com
gr-api-video-asae1b.smoot.apple.com
gr-api-video-ause1b.smoot.apple.com
gr-api-video-ause1c.smoot.apple.com
gr-api-video-ause2a.smoot.apple.com
gr-api-video-ause2b.smoot.apple.com
gr-api-video-ausw2a.smoot.apple.com
gr-api-video-ausw2b.smoot.apple.com
gr-api-video-h-aape1a.smoot.apple.com
gr-api-video-h-aape1b.smoot.apple.com
gr-api-video-h-aapne1a.smoot.apple.com
gr-api-video-h-aapne1c.smoot.apple.com
gr-api-video-h-aapne2a.smoot.apple.com
gr-api-video-h-aapne2b.smoot.apple.com
gr-api-video-h-aaps1a.smoot.apple.com
gr-api-video-h-aaps1b.smoot.apple.com
gr-api-video-h-aapse1a.smoot.apple.com
gr-api-video-h-aapse1b.smoot.apple.com
gr-api-video-h-aapse2a.smoot.apple.com
gr-api-video-h-aapse2b.smoot.apple.com
gr-api-video-h-aeun1a.smoot.apple.com
gr-api-video-h-aeun1b.smoot.apple.com
gr-api-video-h-aeus1b.smoot.apple.com
gr-api-video-h-aeus1c.smoot.apple.com
gr-api-video-h-aeuw1a.smoot.apple.com
gr-api-video-h-aeuw1b.smoot.apple.com
gr-api-video-h-asae1a.smoot.apple.com
gr-api-video-h-asae1b.smoot.apple.com
gr-api-video-h-ause1b.smoot.apple.com
gr-api-video-h-ause1c.smoot.apple.com
gr-api-video-h-ause2a.smoot.apple.com
gr-api-video-h-ause2b.smoot.apple.com
gr-api-video-h-ausw2a.smoot.apple.com
gr-api-video-h-ausw2b.smoot.apple.com
gr-api-video-h.smoot.apple.com
gr-api-video.smoot.apple.com
gr-asae1a.smoot.apple.com
gr-asae1b.smoot.apple.com
gr-ause1b.smoot.apple.com
gr-ause1c.smoot.apple.com
gr-ause2a.smoot.apple.com
gr-ause2b.smoot.apple.com
gr-ausw2a.smoot.apple.com
gr-ausw2b.smoot.apple.com
gr-g-carry-ause1b.smoot.apple.com
gr-g-carry-ause1c.smoot.apple.com
gr-g-carry-ause2a.smoot.apple.com
gr-g-carry-ause2b.smoot.apple.com
gr-g-carry-ausw2a.smoot.apple.com
gr-g-carry-ausw2b.smoot.apple.com
gr-g-carry.smoot.apple.com
gr.smoot.apple.com
guzzoni.smoot.apple.com
seed-falcon-ausw2b.smoot.apple.com
seed-falcon.smoot.apple.com
sis-apse1.smoot.apple.com
sis-ci.smoot.apple.com
sis-euw1.smoot.apple.com
sis-stg.smoot.apple.com
sis-usw2.smoot.apple.com

**Comment by ShadowWhisperer** [comment]
Hi,

They are blocked under wildcard `*.smoot.apple.com`

`https://github.com/ShadowWhisperer/BlockLists/blob/master/RAW/Wild_Apple`

Blocked internally that way. I didn't have the file posted here. *I don't have it as a stand alone file. It produced from a script.

**Comment by ShadowWhisperer** [comment]
For reference, here are some more. *Not sure if active, they were in my ignore list.

api-aka.smoot.apple.com
api-bos.smoot.apple.com
api-glb-abt-nlb.smoot.apple.com
api-glb-aeuw1c.smoot.apple.com
api-glb-ams.smoot.apple.com
api-glb-apne1c.smoot.apple.com
api-glb-apne1d.smoot.apple.com
api-glb-aps1b.smoot.apple.com
api-glb-apse1c.smoot.apple.com
api-glb-apse2c.smoot.apple.com
api-glb-ash.smoot.apple.com
api-glb-atl.smoot.apple.com
api-glb-bln.smoot.apple.com
api-glb-bos.smoot.apple.com
api-glb-che.smoot.apple.com
api-glb-chi.smoot.apple.com
api-glb-dal.smoot.apple.com
api-glb-den.smoot.apple.com
api-glb-drf.smoot.apple.com
api-glb-euc1a.smoot.apple.com
api-glb-euc1b.smoot.apple.com
api-glb-euw1c.smoot.apple.com
api-glb-euw3b.smoot.apple.com
api-glb-euw3c.smoot.apple.com
api-glb-fra.smoot.apple.com
api-glb-gusc1b.smoot.apple.com
api-glb-hkg.smoot.apple.com
api-glb-hou.smoot.apple.com
api-glb-lax.smoot.apple.com
api-glb-lon.smoot.apple.com
api-glb-man.smoot.apple.com
api-glb-mia.smoot.apple.com
api-glb-mum.smoot.apple.com
api-glb-nyc.smoot.apple.com
api-glb-par.smoot.apple.com
api-glb-rno.smoot.apple.com
api-glb-sae1c.smoot.apple.com
api-glb-sea.smoot.apple.com
api-glb-sel.smoot.apple.com
api-glb-sin.smoot.apple.com
api-glb-sjc.smoot.apple.com
api-glb.smoot.apple.com
api-glb-sto.smoot.apple.com
api-glb-tpe.smoot.apple.com
api-glb-tyo.smoot.apple.com
api-glb-use1a.smoot.apple.com
api-glb-use1b.smoot.apple.com
api-glb-use1c.smoot.apple.com
api-glb-usw2b.smoot.apple.com
api-glb-usw2c.smoot.apple.com
api-man.smoot.apple.com
api-sjc.smoot.apple.com
cdn-api-prod.pluto.tvapi-glb-ash.smoot.apple.com
clients4.google.comapi-glb-ash.smoot.apple.com
daypass.api-aka.smoot.apple.com
daypass.api-glb-ams.smoot.apple.com
daypass.api-glb-ap1.smoot.apple.com
daypass.api-glb-ash.smoot.apple.com
daypass.api-glb-atl.smoot.apple.com
daypass.api-glb-bln.smoot.apple.com
daypass.api-glb-bos.smoot.apple.com
daypass.api-glb-che.smoot.apple.com
daypass.api-glb-dal.smoot.apple.com
daypass.api-glb-den.smoot.apple.com
daypass.api-glb-drf.smoot.apple.com
daypass.api-glb-dub.smoot.apple.com
daypass.api-glb-fra.smoot.apple.com
daypass.api-glb-hkg.smoot.apple.com
daypass.api-glb-hou.smoot.apple.com
daypass.api-glb-jnb.smoot.apple.com
daypass.api-glb-lax.smoot.apple.com
daypass.api-glb-lon.smoot.apple.com
daypass.api-glb-man.smoot.apple.com
daypass.api-glb-mia.smoot.apple.com
daypass.api-glb-msp.smoot.apple.com
daypass.api-glb-mum.smoot.apple.com
daypass.api-glb-nyc.smoot.apple.com
daypass.api-glb-osa.smoot.apple.com
daypass.api-glb-par.smoot.apple.com
daypass.api-glb-rno.smoot.apple.com
daypass.api-glb-sea.smoot.apple.com
daypass.api-glb-sel.smoot.apple.com
daypass.api-glb-sin.smoot.apple.com
daypass.api-glb-sjc.smoot.apple.com
daypass.api-glb.smoot.apple.com
daypass.api-glb-sto.smoot.apple.com
daypass.api-glb-syd.smoot.apple.com
daypass.api-glb-tpe.smoot.apple.com
daypass.api-glb-tyo.smoot.apple.com
daypass.smoot.apple.com
e6858.dscc.akamaiedge.netapi.smoot.apple.com
e990.g.akamaiedge.netapi-glb-ash.smoot.apple.com
graph.facebook.comapi.smoot.apple.com
gs-loc.ls-apple.com.akadns.netapi-glb-ash.smoot.apple.com
init.itunes.apple.comapi-glb-ash.smoot.apple.com
ns1.smoot.apple.com
ns2.smoot.apple.com
