### ISSUE TITLE
glpals.com

### ISSUE THREAD

**Issue by yoshimo** [ShadowWhisperer/BlockLists#145]
It is Assisted-GPS Data for some smartphones by the soc vendor. It is downloaded and used locally.

**Comment by ShadowWhisperer** [comment]
If my memory serves correct, my old LG phone used to call out to this, even with no GPS/map app running.

**Comment by yoshimo** [comment]
Well it is used to speed up the time to first fix so it makes sense to get the data in advance so you have it ready when an app wants to pinpoint your location.

**Comment by ShadowWhisperer** [comment]
Since this is not a domain that "should" be active for tracking, it will remain in tracking.
