### ISSUE TITLE
Removing the domains in the Whitelist from the blocklists

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [ShadowWhisperer/BlockLists#146]
I wanna know if it is being implemented or like it should be done manually?(i mean like adding the whitelist manually or it is already filtered from the blocklists. I'm using Pi-hole. Thank You.

**Comment by ShadowWhisperer** [comment]
The domains found in **/Whitelists/Filter** and **/Whitelists/Whitelist** are already removed from the block lists. They exist mainly to help me with building the block lists.
