### ISSUE TITLE
entechremote.com incorrectly added to malware list?

### ISSUE THREAD

**Issue by King-Louis-III** [ShadowWhisperer/BlockLists#147]
entechremote.com is our screen connect (connectwise control) instance.  I'm curious about how it ended up on your malware list?  Was it pulled from another source?

**Comment by ShadowWhisperer** [comment]
Flagged as "**Remote support page [Generic]** / **Potential remote scam landing**"

> These lists are built using custom scripts, and manual additions. (All of my own)   

Source lists are compiled from multiple top million lists, newly registered lists, my honeypots, DNS logs from networks I manage, etc.

**Comment by King-Louis-III** [comment]
Understood.  I'm trying to figure out how this particular entry ended up on your blacklist so I can make sure our domain isn't compromised, or if it came from a different list, how it ended up on their list.  

I ended up here because I found it on another list entirely, and they pointed me to your list as the source, so I'm trying to trace it back to figure out what happened.

**Comment by ShadowWhisperer** [comment]
[Origin](https://tranco-list.eu/latest_list) - Tranco list

**Whitelisted**

_uscomputergroup.com_ added to scanner's Name Server ignore [list](https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Internal/Filters/Whois_NS)

**Comment by King-Louis-III** [comment]
The domain was entechremote.com

Which I don't see in that Tranco list you posted.  I'm not sure what the uscomputergroup.com domain is?

**Comment by ShadowWhisperer** [comment]
- entechremote.com was the domain whitelisted
- Full URL: https://tranco-list.eu/latest_list
Green button, on the right - click drop-down arrow, Download full list
*My Excel popped up with an error. Works fine in Debian

![Capture](https://github.com/ShadowWhisperer/BlockLists/assets/61057625/86569c60-f795-4d9e-a3e2-1c76661e1988)
