### ISSUE TITLE
Question about guard.io

### ISSUE THREAD

**Issue by Jniklas2** [ShadowWhisperer/BlockLists#148]
I just want to know the reason, why `guard.io` was added to the malware list. Sadly the git commit https://github.com/ShadowWhisperer/BlockLists/commit/715ca6ff3ec902f5b0243c63ee6ad8c4b52e92ef only mentions "updated" as the comment.

**Comment by ShadowWhisperer** [comment]
Sus browser extension. Very little info on them.
I've had systems come in to be fixed, wanting it removed. Customers "claim" they didn't install it.

https://www.reddit.com/r/antivirus/comments/n4q3qu/guardio/
