### ISSUE TITLE
re: geo1.presslabs.net

### ISSUE THREAD

**Issue by badmojr** [ShadowWhisperer/BlockLists#15]
Hello!
This domain was recently reported to me as breaking quite alot of sites.
After a quick internet search, I was able to find these sites as being affected through CNAME blocking.

```
blog.hellotds.com
www.siasat.com
blog.bendbroadband.com
```

Here's the report:
```
Hello. This is Cristian from Presslabs Support.
One of our customers notified us that our main geo1.presslabs.net CNAME is being blocked via your domains list block.
How can we remove it from that list?
```

see also: https://www.presslabs.com/about/

**Comment by ShadowWhisperer** [comment]
Hey!

_geo1.presslabs.net_ has been removed, and whitelisted.

Thanks!
Sean H.
