### ISSUE TITLE
All .com blocked

### ISSUE THREAD

**Issue by ValiumBear** [ShadowWhisperer/BlockLists#151]
Needs to be fixed ASAP

https://github.com/ShadowWhisperer/BlockLists/commit/89caa71754d435f200e908bce8589ad530ff6153#diff-6dbe90304c5696795e5f04e654f341a57cefe0e8a021a5a085b70972fc391d06R15756

**Comment by gboddin** [comment]
:shrug: That's just ... wonderful

**Comment by dannywillems** [comment]
Seems updated now c10eeb2

**Comment by ShadowWhisperer** [comment]
Fixed. Not sure how that got in there.
Added addition countermeasures/error checking to issues script that runs before uploading; to prevent this in the future.
Sorry for any issues this may have caused you.
