### ISSUE TITLE
Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [ShadowWhisperer/BlockLists#154]
[i] Target: https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Adult
  [✓] Status: Retrieval successful
  [✓] Parsed 259850 exact domains and 0 ABP-style domains (ignored 1 non-domain entries)
      Sample of non-domain entries:
        - "seksblogger.n"

**Comment by ShadowWhisperer** [comment]
Looks like it was supposed to be "seksblogger.nl". Removed, Thanks!
