### ISSUE TITLE
reship.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#157]
Hi,
You've got this domain blocked under scams. This is a legit mail forwarding business and i've been using them for years

**Comment by ShadowWhisperer** [comment]
Scanning the site, I see no red flags/signs of it using a scam template, indicating that this was a manually added, based on reviews. There's a ton of negative reviews of them, and claims of them being a scam.

Based on your rep with me, it will be removed from the scam list.

Thanks!

**Comment by p1r473** [comment]
Ha cool, I hope my rep with you is good 👼 
These guys give you a mail forwarding address for when you shop online - if I want to order something to my country and they only ship to USA, these guys are great for that

**Comment by ShadowWhisperer** [comment]
You've help out a lot!
I appreciate it. 😃
