### ISSUE TITLE
feedburner.com - false positive

### ISSUE THREAD

**Issue by mtxadmin** [ShadowWhisperer/BlockLists#161]
Several years ago I knew this service. Didn't notice it in your list. Please, remove this false positive.

https://github.com/mtxadmin/ublock/issues/86

**Comment by spirillen** [comment]
feedburner is all google tracking/spying...

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
data/PhishingDatabaseLinks.txt:feeds.feedburner.com
```

#### Sorted result

```css
feeds.feedburner.com
```

### Search result from easylist

```css
fanboy-addon/fanboy_annoyance_thirdparty.txt:||feedburner.com^$image,third-party
fanboy-addon/fanboy_annoyance_thirdparty.txt:||wp.com/www.feedburner.com/fb/$image
```

## Search in [Matrix](https://www.mypdns.org/)


Search results from [Matrix](https://www.mypdns.org) blacklist project

```css
source/tracking/wildcard.list:feedburner.com
```


Found these RPZ records from My Privacy DNS
```sql
id      domain records  type    content
6526583 *.feedburner.com.tracking.mypdns.cloud  CNAME   .
6535579 feedburner.com.tracking.mypdns.cloud    CNAME   .
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://www.mypdns.org/) for this knowledge
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by ShadowWhisperer** [comment]
Will be staying in my list.

`Feedburner, Inc. is a web feed management service primarily for monetizing RSS feeds, primarily by inserting targeted advertisements into them. It was founded in 2004[1] and acquired by Google in 2007. ` - Wikipedia
