### ISSUE TITLE
[Bloat list] Google products issue - script.google.com

### ISSUE THREAD

**Issue by K-mikaZ** [ShadowWhisperer/BlockLists#165]
Apps Script is a cloud-based JavaScript platform that lets you integrate with and automate tasks across Google products.
https://developers.google.com/apps-script

[Google Apps Script Home](https://script.google.com/home)

Please whitelist `script.google.com`

**Comment by ShadowWhisperer** [comment]
I'm going to have to think/do some more research on that one.
It can be used for tracking.

https://ravgeetdhillon.medium.com/how-to-track-email-opens-with-google-apps-script-df65a922c2cd

**Comment by spirillen** [comment]
it is used for a lot more nasty things like that... we are talking phishing, malicious, spyware etc here, this one should even just for security measures be a personal choice of whitelisting,

**Comment by ShadowWhisperer** [comment]
Due the domain being in **Bloat** and not the main 3 (Ad/Track/Malware) it will remain blocked. The risks far outweigh the usefulness. *I have not a website fail to work, because this is blocked. Bloat, Junk, and Risk are more of my personal lists.
