### ISSUE TITLE
vip-zona.com

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#167]
Hey friend. I can see you are storing `vip-zona.com` in your adult list, however, over the past couple of days, it have not been possible for me to connect to the domain.

Do you happen to have some knowledge you can share??

------------

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
data/hosts-file.psh.csv:mail.vip-zona.com
data/hosts-file.psh.csv:ns1.vip-zona.com
data/hosts-file.psh.csv:ns2.vip-zona.com
data/hosts-file.psh.csv:vip-zona.com
data/hosts-file.psh.csv:www.vip-zona.com
```

#### Sorted result

```css
mail.vip-zona.com
ns1.vip-zona.com
ns2.vip-zona.com
www.vip-zona.com
```

### Search result from easylist

```css
```

## Search in [Matrix](https://www.mypdns.org/)

Search results from [Matrix](https://www.mypdns.org) blacklist project

```css
source/porn_filters/imported/adult.ShadowWhisperer:vip-zona.com
```

**Comment by spirillen** [comment]
![image](https://github.com/user-attachments/assets/559caa3a-52e9-4ccb-8fbf-a4b98bdbd529)

**Comment by ShadowWhisperer** [comment]
Looks like a Hentai site. It eventually gives me a Cloudflare timeout error.

Guessing these are all the same
```
vip-zona.biz
vip-zona.com
vip-zona.net
```

**Comment by spirillen** [comment]
Yep, leaving them out of my list, as they seems discontinued.

**Comment by ShadowWhisperer** [comment]
Removed from my list, now, also
