### ISSUE TITLE
malware list false positive on steamcommunity.com

### ISSUE THREAD

**Issue by Codfish246** [ShadowWhisperer/BlockLists#168]
as title says
![firefox_2J6Z3LH0dS](https://github.com/user-attachments/assets/0445eff3-86bb-45ce-90d7-4eb5303faa93)

**Comment by Renari** [comment]
https://github.com/ShadowWhisperer/BlockLists/commit/96928053ca9e118a57c4745671b7ada0f0dbb78d

Looks like it was already fixed in this update, refresh your list.
