### ISSUE TITLE
Request for Removal of hiverhq.com from BlockLists/Lists/Malware

### ISSUE THREAD

**Issue by SourajChakraborty** [ShadowWhisperer/BlockLists#171]
Hello @ShadowWhisperer 
We are an email management system and can run multi-channel help desks within your inbox of gmail. Hiver strengthens team collaboration and business communication across email, live chat, chatbot, knowledge base, and voice communication.
We are running scan with security scorecard and multiple VAPTs and audits. With SOC2 and ISO 27001 compliance for years. 

Can you please remove hiverhq.com from your list, or give us some information about why we are on the list, so we can fix it? We'd really appreciate it! For any additional details please refer to our website https://hiverhq.com/ or reach out to security@hiverhq.com 

Regards
Souraj Chakraborty
@Hiver InfoSec Team.

**Comment by ShadowWhisperer** [comment]
**Whitelisted**. Scan results = clean. False positive. No further notes.
