### ISSUE TITLE
False positive - c6.patreon.com

### ISSUE THREAD

**Issue by sefinek** [ShadowWhisperer/BlockLists#176]
c6.patreon.com

![{8041E6C9-3D21-48D5-A8A2-ACA2B785038D}](https://github.com/user-attachments/assets/f449a950-65c7-4cb9-9f86-7f7ef8120cd7)

**Comment by ShadowWhisperer** [comment]
Whitelisted.

More context: `https://c6.patreon.com/becomePatronButton.bundle.js`
Breaks the support button.
