### ISSUE TITLE
Domains breaking embedded videos

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#18]
These domains breaking embedded videos on sites such as:
https://www.zerohedge.com/markets/pa-home-total-loss-after-charging-tesla-driveway-spontaneously-combusts
The CDNs are Content Delivery Networks and are responsible for serving up a variety of static content
cdn.abcotvs.net
dcf.espn.com
![image](https://user-images.githubusercontent.com/9235633/143718714-3e45c83d-185a-45bd-ab59-d05ad5c7f914.png)

**Comment by ShadowWhisperer** [comment]
_cdn.abcotvs.net_ has been whitelisted.  I am unable to get the video to play, even on a system with all filtering turned off. I will look into it further.

**Comment by p1r473** [comment]
dcf.espn.com is also required, its also on your list

cdn.abcotvs.net also too but I didnt see it on your list.

**Comment by ShadowWhisperer** [comment]
This is what I get with all filters turned off. No extensions. Stock hosts file.  I tried multiple browsers, DNS resolvers, and operating systems. Same thing on my phone, using cell data.   I don't question the validity of those domains. I want to verify if for myself. I'll keep working on it.

![1](https://user-images.githubusercontent.com/61057625/143728045-98904b00-69b7-4939-ae66-8d8ef1e2f6ed.PNG)

I click the video to start playing and it does this.

![2](https://user-images.githubusercontent.com/61057625/143728048-88b832a8-c397-4664-aad9-ff9e7e60cf80.PNG)

**Comment by ShadowWhisperer** [comment]
Looks like the site is pulling the embedded video from _abc7.com_.
This player is the same: https://abc7.com/beatles-get-back-peter-jackson-director/11270260/

Both   _cdn.abcotvs.net_ and _dcf.espn.com_ have been whitelisted.

Thank you!
- Sean H.
