### ISSUE TITLE
unblockninja.com - False Positive

### ISSUE THREAD

**Issue by SeriousHoax** [ShadowWhisperer/BlockLists#181]
Present in the Malware list. 
It should be unblocked.
Example site: `https://1337x.unblockninja.com/`

**Comment by ShadowWhisperer** [comment]
Moved to **Tunnels**

**Comment by spirillen** [comment]
Tunnels? what are that category covering?

**Comment by ShadowWhisperer** [comment]
`Tunnels          VPNs & Proxies  `
