### ISSUE TITLE
Invalid Domains

### ISSUE THREAD

**Issue by j-moriarti** [ShadowWhisperer/BlockLists#2]
the following domains have problematic characters (dns servers return "Non-existent domain"):

list -------------------------- line --------- domain ------------------------------- invalid char

Dynamic ------------------- 430 -------- dyndns-ofﬁoe.com --------------------- ﬁ
Dynamic ------------------- 485 -------- endoﬁnternet.net ---------------------- ﬁ
Dynamic ------------------- 811 -------- is-a-ﬁnancialadvisor.com ------------- ﬁ
Dynamic ------------------- 875 -------- is-not-certiﬁed.com -------------------- ﬁ
Malware ------------------- 1437 ------- č16857.biz ------------------------------ č
Malware-Scam-Typo ---- 6409 ------- č16857.biz ------------------------------ č

**Comment by ShadowWhisperer** [comment]
Thanks for the find! They will be removed from the lists in the next update. I appreciate your help!
