### ISSUE TITLE
[false-positive] s3.ap-northeast-2.amazonaws.com

### ISSUE THREAD

**Issue by dnmTX** [ShadowWhisperer/BlockLists#22]
Hi there Sean @ShadowWhisperer 👋 
Been using some of your lists for a while now and just today stumbled on one false-positive: `s3.ap-northeast-2.amazonaws.com`
Samsung's website is using the domain for driver/firmaware downloads.
**Test Page:**
https://www.samsung.com/semiconductor/minisite/ssd/download/tools/
**Test Link:**
https://s3.ap-northeast-2.amazonaws.com/global.semi.static/SAMSUNG_SSD_970EVO_Plus_ISO_190513/7ES357322A6707A720E1A71EF11A3BE1EED819E011D317626415F0281A78151C/Samsung_SSD_970_EVO_Plus_2B2QEXM7.iso

Whitelisting would be appreciated and keep up the good work 👍

**Comment by ShadowWhisperer** [comment]
Hey there!

It has been whitelisted.

Thank you!  Much appreciated!  =D

**Comment by dnmTX** [comment]
Sean @ShadowWhisperer just FYI for now. See https://github.com/r-a-y/mobile-hosts/issues/18 as you have it listed as well.
Will let you know eventually 👍

**Comment by ShadowWhisperer** [comment]
Odd. I've had _c.paypal.com_ blocked for quite some time.  I buy stuff on Ebay, at work.  Monday is the most recent. I haven't had any issues.  I do have it set to ask for my password every time. I don't use PayPal for anything else. I use a Windows based laptop, every time. Located in USA.

**Comment by dnmTX** [comment]
> I do have it set to ask for my password every time

That si what probaly break things on my end as usually when i choose PayPal it just takes me to confirm the payement.
Sean @ShadowWhisperer advise how to set up to ask for password please.
I was just thinkering with my Ebay settings and didn't see option for it.
Thanks 👍

**Comment by ShadowWhisperer** [comment]
I do not see an option for it either. I use an extension to auto delte my cookies. It deletes the login cookie after I close the window. 

Here is the URL it calls out to: **https://c.paypal.com/da/r/fb.js**

You could try clearing your cookie/cache for PayPal.
Firefox: [https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox)
Chrome: [https://support.google.com/chrome/answer/95647?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cdelete-cookies-from-a-site](https://support.google.com/chrome/answer/95647?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cdelete-cookies-from-a-site)

**Comment by dnmTX** [comment]
No such a option exist anymore and anything related to auto login or such is off on my end.
I'll block the PayPal cookies and see if that helps but so far whatever i could find about it,it looks like is just part of the PayPal's 
payment process. See: https://www.paypal-community.com/t5/REST-APIs/PayPal-Send-Money-to-friends-to-save-0-25/m-p/2261890#M5100
Worst case scenario,i'll just whitelist it on my end,i guess 🤔

**Comment by dnmTX** [comment]
Disabled two additionl things as well,let's see if that will do the trick:
![One Touch Has Been Turned Off](https://user-images.githubusercontent.com/34774426/144367747-08ffc3db-40d8-49a2-80e6-9713fd9836be.png)

![Security Settings](https://user-images.githubusercontent.com/34774426/144367756-a63bf9e0-a15b-463d-923c-4d1cdb1239f5.png)

**Comment by ShadowWhisperer** [comment]
If it is required to work, let me know and I'll whitelist it.

**Comment by dnmTX** [comment]
Thanks Sean @ShadowWhisperer 👍

**Comment by ShadowWhisperer** [comment]
No problem.  I made a note in _Whitelist_. Hopefully it'll help out anyone else looking for information on it.
