### ISSUE TITLE
geo.clients.config.office.akadns.net

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#23]
This domain is a CNAME for clients.config.office.net
This site is for client configuration to the Office 365 environment
I believe this may be a false positive

I know it starts with geo but I dont think its a tracking domain

**Comment by ShadowWhisperer** [comment]
We already went over this. Also posted by you...  If you are going to open an Issues, give me in depth details.

_https://github.com/ShadowWhisperer/BlockLists/issues/12_

> I have yet to see a breakage by blocking it. I install Office almost daily at work (Computer Tech), Office Home & Student, Home & Business, & 365, Seat management, account transfers, and activation all work.

**Comment by p1r473** [comment]
Whoops, apologies for the dupe
