### ISSUE TITLE
widget.sndcdn.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#24]
This is the SoundCloud widget
I dont believe this is malicious or related to spyware or adware
Example site where its blocked: https://www.sprottmoney.com/blog/The-Upside-Down-Year-in-Gold-and-Silver-Erics-Yearly-Wrap-Up
![image](https://user-images.githubusercontent.com/9235633/145650003-0cfc7157-517e-4c41-8621-8642d6341400.png)

**Comment by ShadowWhisperer** [comment]
Whitelisted! Thank you!
- Sean
