### ISSUE TITLE
widget.nfusionsolutions.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#25]
This is a widget to display precious metals prices on a website
I dont believe this is malicious
Example: https://www.sprottmoney.com/blog/The-Upside-Down-Year-in-Gold-and-Silver-Erics-Yearly-Wrap-Up

**Comment by ShadowWhisperer** [comment]
I don't see it blocked in any of my lists, but it has been whitelisted.

Thanks!
- Sean
