### ISSUE TITLE
May each list contain a designated and consistent format?

### ISSUE THREAD

**Issue by T145** [ShadowWhisperer/BlockLists#26]
Some lists have only your staple header alongside the designated content, and others include comments on the same lines.
The list content can change formats, which can interfere with how others process your lists.
Removing the comments and keeping a consistent format across the every list would help everyone.
Perhaps you could edit the header to include a line for notes or include a footer that becomes the notes section.

**Comment by ShadowWhisperer** [comment]
Hi,

I have thought about that. I figured including additional information on the less used lists would mitigate some of the questioning/reasons for blocking them.

The following will clean it up. (Bash)
`grep -v ^'\#' LIST | awk '{print $1;}' | grep '\.`'

- Sean

**Comment by T145** [comment]
You can just do `mawk '$0~/^[^#]/{print $1}' list.txt` on anything you have now and it will generate the raw hosts. However it's most efficient to have one format to operate on so expressions do not have to be used on each line, or at the very least cheaper operations can be the alternative.

**Comment by ShadowWhisperer** [comment]
I'll take it under advisement. :+1: In the (almost) 2 years I've shared these lists, no one has mentioned removing the comments.

**Comment by ShadowWhisperer** [comment]
I crated a new folder **RAW** that does not have any comments, and has the wildcards separated from the rest of the lists.

**Comment by spirillen** [comment]
I'm a fan of your wild_category files, they will become very easy to incorporate for many blacklist

**Comment by T145** [comment]
Were the Wild lists available before? What's their purpose?

**Comment by ShadowWhisperer** [comment]
The wild lists were merged with the full list before. Everything in wild i block *.WildDomain
