### ISSUE TITLE
Cooperating about the BlackLists

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#28]
Hi ShadowWhisperer, I can see in your files that we a similar approach to how things should be handled when it comes to distributing the blacklist records.

This said there are also a few diffs that should be overcome by a few tweaks, yet a bit time consuming, but I think we could end up getting stronger together by cooperating rather that "fighting" each other by holding this similar projects and this close Blacklists, not at least when it comes to the adult, Adware, tracking and malicious. The biggest diff I see is:

1. You uses GH, I uses my tracking free [mypdns.org](https://mypdns.org/)
2. I uses the issue board for storing documentation / comment on each records
3. I let the end users determine for them self which unwanted domains they would let through. (https://mypdns.org/my-privacy-dns/matrix#faq). This is done as the DNS RPZ have it [rpz-passthru.](https://mypdns.org/mypdns/support/-/wikis/RPZ-record-types#the-passthru-action-cname-rpz-passthru) whitelisting feature build-in
4. You are doing [hosts](https://mypdns.org/mypdns/support/-/wikis/dns/DnsHosts) ([RFC:952](http://tools.ietf.org/html/rfc952)) style blacklisting, while `my privacy DNS` are toward DNS RPZ

I do believe together can build something so much stronger to the beneficiary of not just our self saving a bunch of hours but more the end users as they get twice the manpower, twice the amount of information to make a decision from, but also a stronger Blacklist.

Is this something that in some way can be of any interest to you?

**Comment by ShadowWhisperer** [comment]
Hey,

I don't document why domains are blocked, other than what I post here.

Tough part of merging, or changing my file structure; I have a lot of home and business customers that use my malware, and scam lists. I put it on every computer I setup/work on. Changing anything would break those.  (Looking at it now, I should have done the structure differently.) I don't personally use Github. I upload the lists in an encrypted file to Dropbox (encrypted, do to paranoia), and update from there.

I use Dnsmasq and Dnscrypt, As far as I know, Dnsmasq doesn't support DNS RPZ. (I could be wrong). I'm not familiar with what that is.

I'm not looking to merge, at the moment.  If there's something specific you want me to do, let me know. (I don't share my scripts)

- Sean

**Comment by spirillen** [comment]
Hey Sean, thanks for your replies (#27 + #28)

My intention was as you mention to merge our project, but not as such merging the lists them self, it more the finding and comment (knowledge) to why it is added to a lists. That is actually better described [here](https://mypdns.org/infrastructure/matrix-rocks/www.matrix.rocks/-/blob/master/README.md) without being that good.

> I don't document why domains are blocked, other than what I post here.

If you looks at my issues, you'll see I rarely add much more to mine, there is exceptions, as it is required, but not in general. (I usually uses the ublock origin logger to document relation)

> Tough part of merging, or changing my file structure; I have a lot of home and business customers that use my malware, and scam lists. I put it on every computer I setup/work on. Changing anything would break those. (Looking at it now, I should have done the structure differently.)

Setup redirect (symlinking)

> I use Dnsmasq and Dnscrypt, As far as I know, Dnsmasq doesn't support DNS RPZ

True, it is not even RFC compliant, but it understand wildcards and there is a version (fork) that understand regex as well. 

> I upload the lists in an encrypted file to Dropbox (encrypted, do to paranoia), and update from there.

Isn't dropbox not just another honeypot to collecting privacy invasive data? :smirk: 

> I'm not looking to merge, at the moment. If there's something specific you want me to do, let me know. (I don't share my scripts)

If you would commit any new adult records to [Porn Records](https://mypdns.org/my-privacy-dns/porn-records#submit-contribute) and AdWare, Tracking etc to [the matrix](https://mypdns.org/my-privacy-dns/matrix#issue-templates-quick-links)

I would absolutely be a happy man.

> #27 

About the same story here, That I came to manage a adult blacklist is however a bit obscure as I previously actually ran several of these site my self :rofl: . I had the resources available, why not make money to a stake..

Tiny optimization on your regex.

```bash
#GoatStats
if [[ -n "$(grep -E '^(analytics|stats|stat|counter|goat)\.' <<< "$Site")" ]]
then
    Info="$(timeout -s KILL 5 curl -sA "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/89.0" "https://$Site/count.js")"

    if [[ "$(grep -ic 'goatcounter' <<< "$Info")" -gt '5' ]]
    then
        echo "$Site" >> /root/Results/Tracker; Found='1';
        return
    fi
fi
```

What I've done is grouping the search strings as they all use the `^` start with and with a dot `.` you can group the or `|` values

The results from these runs would probably be welcome as even I blocks the goat, it is build to be obfuscated behind CNAME's and reverse proxies.

**Comment by ShadowWhisperer** [comment]
`Isn't dropbox not just another honeypot to collecting privacy invasive data? 😏`

It is :satisfied:. That's why I use character substitution on the content, convert it to binary, and then use a 4,096 key password to decrypt it. (ccrypt) I use the browser interface to manually upload it, instead of the client.

`Setup redirect (symlinking)`
I will look into that. I keep my wildcards separate from the normal list, and combine them when I upload, to Github. I was thinking of a way to better upload them.

`if [[ -n "$(grep -E '^(analytics|stats|stat|counter|goat)\.' <<< "$Site")" ]]`
Thanks! I didn't know that was a thing. Learned something new today.

------------------------------------------------

The _mypdns.org_ site -->  I made an account and setup SSH. I'm not familiar with the contributing part. Are you wanting me to fill this out, when I add new domains?

`https://mypdns.org/my-privacy-dns/porn-records/-/issues/new?issuable_template=Strict_Adult_contents
https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issuable_template=Tracking`

If so, which "Master" list should I remove mine from, first?  Example:  comm -23 MyList YourList > UploadList

**Comment by spirillen** [comment]
**_Quick answers_**

> I will look into that. I keep my wildcards separate from the normal list,

Have a peak on the structure here https://mypdns.org/my-privacy-dns/porn-records#file-structure-explained it might give you some idea's They are designed to meat all sorts of blacklists I could think of.

>  when I add new domains

Just the issue, as the I like you have private scripts to manage the important parts :wink: And the main idea is to give everyone the opportunity to comment, dispute etc to any commits and why it is commit, also give users the knowledge needed to determine if they would whitelist any record. This is also why I wouldn't expect a complete merge of our lists, mostly the knowledge.

> If so, which "Master" list should I remove 

Will et to this one tomorrow as it differs between the two repos. 

comm is not the best tool here,  a function is more optimal as is will remove exact matches despite order, comm requires the lists to equally ordered versus grep.

```bash
remove-lines() (
        # usage: remove-lines file-with-lines-to-remove file-to-remove-lines-in
        remove_lines="$1"
        all_lines="$2"
        tmp_file="$(mktemp)"
        grep -Fvxf "$remove_lines" "$all_lines" > "$tmp_file"
        mv "$tmp_file" "$all_lines"
)
```

**Comment by spirillen** [comment]
> If so, which "Master" list should I remove mine from, first?

After reviewing your lists, I think the easiest way forward from here is to find the differences in the lists and then exchange those, manually via issue ticket one by one. in old fashion way, manual labor.

The adult list, I would like to trim down from my existing lists and then use it as a third party source until it have been "emptied" for records, just like I do with the old @clefspeare13 list https://mypdns.org/my-privacy-dns/porn-records/-/tree/master/submit_here/imported

You also talking about re-ordering your sources.

**Comment by ShadowWhisperer** [comment]
Sorry for the delayed reply. I haven't been feeling great the last couple days. Got worse Thursday afternoon.  Having a hard time staying awake/focusing...

If there's false site, let me know.  The script I made to find these, give me a probability score for the site. I then make sure the site does not redirect. If it does, I investigate that site.  I've noticed a lot of site lately that have a legitimate looking name, but are porn. Example: _BestDentalSchool.com_ (this one is parked, just using the name as an example)

Do I use the "Replace" button when I upload to your site, or does it automatically pull from Github?

**Comment by spirillen** [comment]
That's ok we are humans.

> Do I use the "Replace" button when I upload to your site, or does it automatically pull from Github?

Could you make a screenshot of that, I'm not entirely sure about what you mean here!

**Comment by ShadowWhisperer** [comment]
![Capture](https://user-images.githubusercontent.com/61057625/147858716-687c0de6-f651-4a45-a5e2-dbafb697a989.PNG)

**Comment by spirillen** [comment]
Uh no no no  use the edit other wise otherwise you might just end up re-adding what was moved to the right files with an issue attached to it :smile: 

![image](https://user-images.githubusercontent.com/44526987/147860325-7da2842a-6eee-43b5-bc61-8e7622e4331a.png)

Ass you will see, there is a mango of a roughly 35000 records compared to yours 

However the most optimal would be if you could make them as issues, it is 3 pastes 

1 in title
2 in the domain and *.domain

I'll take care of the rest, trying to teach @Rexadev how to handle issues and he is very keen to this subject, so I predict he will be a huge assets here

There is also a API you can use... (If you are a better coder than I am) https://mypdns.org/help/api/index.md

--------
IF, then

Don't be to upsets about the screenshot if it is cursing you troubles. solid submitter always gets some credit as it in any other directions is a time saver for me, Just to mention for the API way, there is a thread by https://mypdns.org/nada in https://mypdns.org/mypdns/support/-/issues/254

**Comment by Rexadev** [comment]
> I'll take care of the rest, trying to teach @Rexadev how to handle issues and he is very keen to this subject, so I predict he will be a huge assets here

sure

**Comment by Rexadev** [comment]
> . I had the resources available, why not make money to a stake.

How you get paid?

**Comment by spirillen** [comment]
> > . I had the resources available, why not make money to a stake.
> 
> How you get paid?

Paid?? Hmm I would like to know to :smile: This is free time, Open Source not for profit. But you can do a lot of good work and we find a sport to your Coffee banner [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/X8X37FUGU)
