### ISSUE TITLE
Tracking: selfishsnake.com

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#30]
I believe this domain is an Tracking domain(s) --> which should be blocked as..

- [X] Wildcarded
- [ ] Single domain blocking

```python
selfishsnake.com   CNAME . ; Tracking
*.selfishsnake.com   CNAME . ; Tracking
```

## Relevant comments
This domain is used by [`getadmiral.com`][getadmiral] to collect your surfing habits and the are using a variety of scripts to generate a personal identification of you and your devices. Follow [getadmiral][getadmiral] for updates.

You can always find the latest list of Admiral's Active domains in https://mypdns.org/-/snippets/42

## Screenshots
This text appears on all Admirals owned domains

![Screeshot](https://user-images.githubusercontent.com/3980843/29331670-df921aa0-81c2-11e7-89aa-e95bab2b8cb9.png)

## Relevant External sources
- https://mypdns.org/my-privacy-dns/matrix/-/issues/4187

[getadmiral]: https://mypdns.org/my-privacy-dns/matrix/-/issues/3023

**Comment by ShadowWhisperer** [comment]
It is in my list. Not sure how to check the history on Github, when it was added.
_35.201.103.212_ Is owned by **Leven Labs** (Tracking)

I posted the IPs I know, here
`https://raw.githubusercontent.com/ShadowWhisperer/IPs/master/Other/Ads`
`https://raw.githubusercontent.com/ShadowWhisperer/IPs/master/Other/Trackers`

**Comment by spirillen** [comment]
git blame <file> | grep 'What-ever-you-search'

**Comment by spirillen** [comment]
PS: should only be in your tracing list
