### ISSUE TITLE
Merging UrlShortners into mypdns

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#33]
Hi @ShadowWhisperer i'm about importing all your ulrshortners into my equivalent redirectors, but a few troubles me

- `dupinmonig.weebly.com` Can't access the subdomain... Even that I got it [here](https://mypdns.org/my-privacy-dns/matrix/-/issues/42) and I have a FP report here https://mypdns.org/my-privacy-dns/matrix/-/issues/43, the question most be. What is your believe, should it stay or should it go?
- `fsgko29oapsaasz.appspot.com` returns a 404
- `online-dating-steps.com` >>Default campaign not found<<

Are you able to bring some light over any of these

**Comment by ShadowWhisperer** [comment]
Uuum, I'm not seeing those in either the main list, or **Testing**
They must have been removed from **Testing**, as I do see them in my skip list (I don't have the skip list posted anywhere)

Side question:
I've removed parked Adult domains and added more to the link below, but it just shows me the old list everytime I open it.
`https://mypdns.org/my-privacy-dns/porn-records/-/edit/master/submit_here/imported/adult.ShadowWhisperer`

**Comment by ShadowWhisperer** [comment]
The following are no longer in use, and have been removed from the main list

```
bridg.li
casim.ir
cutturls.com
jho.click
kaa.im
shortener.page
snick.ly
```

**Comment by spirillen** [comment]
> I've removed parked Adult domains and added more to the link below, but it just shows me the old list everytime I open it.

did you remember to make the MR (Merge Request) otherwise they should be hanging as branches.

Will investigate this later, I'm about to eat my dinner.

About the original question then I tested the `https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/UrlShortener`

**Comment by spirillen** [comment]
Found your changes, as expected, you forgot the MR part :smile: 

![image](https://user-images.githubusercontent.com/44526987/147974561-6237e9e3-b742-48aa-a25a-42ed67dec85e.png)

Merge request: https://mypdns.org/my-privacy-dns/porn-records/-/merge_requests
![image](https://user-images.githubusercontent.com/44526987/147975644-b5e3f9b1-e722-4bcd-b2ec-b30160f7f0db.png)

Select the source (Your new branch that was create on save)
![image](https://user-images.githubusercontent.com/44526987/147975746-244dc8b1-19d9-4172-b737-c3bb5b59870d.png)


Add some descriptive text, and ig you feel like it you can fill out the drop down's. Leave the Delete and Squash commit, marked.
![image](https://user-images.githubusercontent.com/44526987/147975872-d2f51904-5a7a-400a-bfa4-4cc9cdfaf5c0.png)


- https://mypdns.org/my-privacy-dns/porn-records/-/merge_requests/15
-

**Comment by spirillen** [comment]
Now I have merged all your domains from the urlshortner list so you should now add changes to mypdns and then import to your self to avoid doubles and merge hells

**Comment by ShadowWhisperer** [comment]
I feel like an idiot. I clicked on the **New Merge Request** button. Brought to here,
![1](https://user-images.githubusercontent.com/61057625/147990197-16597a5b-5303-4e07-b116-06b2020f11bb.PNG)

I'm not sure what to do from there

**Comment by spirillen** [comment]
Pick from "Select source Branch" Don't feel like a idiot we all had our first day in school sometime

But as said, I prefer issues, it is way easier to keep track of what was solved and what is new
