### ISSUE TITLE
odc-web-geo.onedrive.akadns.net is a CNAME for onedrive.live.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#34]
odc-web-geo.onedrive.akadns.net is a CNAME for onedrive.live.com
If you use CNAME Deep Inspection like I do, blocking this will break OneDrive

**Comment by ShadowWhisperer** [comment]
More information needed.

I am unable to reproduce issue. Multiple Windows 10 systems in sync. All connected over a custom (my own) Debian router. All DNS traffic is forwarded to me, and all encrypted DNS is blocked. Everything works fine. Chrome and Firefox also work fine.

**Comment by p1r473** [comment]
I see it is being blocked by CNAME Deep Inspection for odc-web-geo.onedrive.akadns.net
![image](https://user-images.githubusercontent.com/9235633/148570471-0544e313-00fa-4817-9ce0-50f18e97d451.png)

![image](https://user-images.githubusercontent.com/9235633/148570762-64705b55-c85b-4c69-b92a-3cce1bda8e6e.png)
https://docs.pi-hole.net/ftldns/configfile/

Basically the CNAME Deep Inspection option says, if you blocked a CNAME, you blocked what it's a CNAME for 

Here is a picture of when I try to visit onedrive.live.com
![image](https://user-images.githubusercontent.com/9235633/148570371-cb555aae-8fd0-4a80-967b-b60fa1dc6f45.png)

**Comment by ShadowWhisperer** [comment]
_CNAME_DEEP_INSPECT_ appears to just be a toggle for appears is the parsed logs (Log you see, not the actual log from dnsmasq).

I do not run Pihole. I see the log as raw (containing everything).

```
query[A] ondrive.live.com from 127.0.0.1
	 forwarded ondrive.live.com to 1.1.1.1
		reply ondrive.live.com is <CNAME>
		reply a-0010.a-msedge.net is 204.79.197.212

```

Hmm. It could be a regional thing, or maybe something to do with the resolver ?
I'm gonna remove it for now. I'll keep an eye on it. I block OneDrive on my own network, anyway.
