### ISSUE TITLE
Cloom.com

### ISSUE THREAD

**Issue by totalimmersion** [ShadowWhisperer/BlockLists#35]
Hi I believe I found a false positive on the malware list
This domain is a sport/fitness website and not a malware website: https://github.com/ShadowWhisperer/BlockLists/blob/490efd23cb31d1c3d7d059f1c8a68bed57993391/Lists/Malware#L4713

Thanks

**Comment by ShadowWhisperer** [comment]
It has been whitelisted.

Thanks!
- Sean
