### ISSUE TITLE
Adware- tracking domains 18. Jan 2022

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#37]
Today's harvest of tracking and adware servers

| domain | Category | issue |
| :--- | :---: | ---: |
| extreme-dm.com | Tracking | 4365 |
| latinwayy.com | AdWare | 4364 |
| ilyf4amifh.com | AdWare | 4363  |
| loboclick.com | AdWare | 4362  |
| sunsetencyclopaedia.com | AdWare | 4351  |
| 9f3b5a24d5.com | AdWare | 4360  |
| ravenousdrawers.com | AdWare | 4342  |
| stickyadstv.com | AdWare | 4366 |
| nbcuni.com | Tracking | 4367 |
| sersh.com | Adware | 4368 |
| adultsense.info | AdWare | 4369 |
| adultsense.net | AdWare | 4370 |
| adultsense.com | AdWare | 4371 |
| imrworldwide.com | Tracking | 4375 |
| researchnow.com | Tracking | 4377 |
| dotomi.com | AdWare | 4378 |
| spotxchange.com | AdWare | 4376 |
| admantx.com| AdWare | 4379  |
| nbcudigitaladops.com | Tracking | 4380 |

**Comment by ShadowWhisperer** [comment]
I will check em out. Thanks!

**Comment by spirillen** [comment]
Your welcome By the way found to :fish: 

`premiums-gift.com` and `discqrde.com`

**Comment by ShadowWhisperer** [comment]
I had these under normal Ads. It doesn't really mater to me. As long as they're blocked. It's kinda tough to differentiate ads and malicious Ads. Without examples, when originally added. I see examples under the issue number on Matrix. :thumbsup:
```
admantx.com        #https://www.crunchbase.com/organization/admantx
adultsense.com
adultsense.info
adultsense.net
dotomi.com
latinwayy.com
loboclick.com
spotxchange.com
stickyadstv.com
```


I am unable to resolv _9f3b5a24d5.com_
Even with _9.9.9.10_ DNS. I even tried third party websites and lookup IPs. Must be shutdown already ?

**Comment by spirillen** [comment]
Try with drill for those phish

`9f3b5a24d5.com` Seems solved for now and the same with `premiums-gift.com`
which is super for the public
