### ISSUE TITLE
reported 26. jan 2022

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#40]
Hey @ShadowWhisperer here is the todays harvest of ad- and tracking

## Tracking
```
emarsys.net
tv2zanalytics.com
```

## Ads
```
nxuktkuoazvizd.com
p4ym.com
zlajnpfqgsleo.com
55b41bef46.com
quenchskirmishcohere.com
cohabitrecipetransmitted.com
writtenanonymousgum.com
juvenilebind.com
spidersmerithenceforward.com
elizabethclowneasy.com
slavesenviablegrammar.com
latereshi.pro
rycuvaphy.com
dogcollarnearest.com
additionalcasualcabinet.com
felonlosel.com
metopeharriet.com
saumonpipidae.com
briskedmiskept.com
kareaumatzot.com
waymarkgentiin.com
mildewtali.com
enrilov.info
beastintruder.com
a5a0976123.com
dogcollarnearest.com
elizabethclowneasy.com
latereshi.pro
slavesenviablegrammar.com
rycuvaphy.com
spidersmerithenceforward.com
juvenilebind.com
55b41bef46.com
writtenanonymousgum.com
cohabitrecipetransmitted.com
quenchskirmishcohere.com
```

@PyFunceble test results

Status      Percentage   Amount      
----------- ------------ ------------
ACTIVE      100%         38          
INACTIVE    0%           0           
INVALID     0%           0

**Comment by ShadowWhisperer** [comment]
Thanks! They have been added.

**Comment by spirillen** [comment]
Extras:

```
limpstronglyer.com
withoutmotivation.com
youngestsow.com
system-notify.app

```

**Comment by spirillen** [comment]
> It looks like this one is adult, not an ad. `p4ym.com`

At my end it is redirecting to `exoclick.com` straight up

https://mypdns.org/my-privacy-dns/matrix/-/issues/4498#relevant-comments

**Comment by ShadowWhisperer** [comment]
Strange :woozy_face:

I saw the two ad servers _reporo.net_, and _exoclick.com_ get requested, but I had them blocked.

**Comment by spirillen** [comment]
```
trustedcpmrevenue.com
effectivedisplaycontent.com
```

**Comment by ShadowWhisperer** [comment]
Got em.

Not sure what the rocket icon means, but I'm gonna use it. :)

**Comment by spirillen** [comment]
> Got em.
> 
> Not sure what the rocket icon means, but I'm gonna use it. :)

I take it as well done :wink:
