### ISSUE TITLE
NSFW: youporn.beer

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#42]
`youporn.beer` redirects to `youporn.fyi` = waste of good bites

> https://mypdns.org/my-privacy-dns/porn-records/-/issues/36336 & https://github.com/easylist/easylist/pull/10548

**Comment by spirillen** [comment]
Found one more sharked on the way

`javsexmovie.com` 

https://mypdns.org/my-privacy-dns/porn-records/-/issues/4089

**Comment by spirillen** [comment]
Adware, Popunder `grytyshosy.pro` https://mypdns.org/my-privacy-dns/matrix/-/issues/4574 Found on `pornfreee.com`

**Comment by ShadowWhisperer** [comment]
Thanks!
