### ISSUE TITLE
pushbullet.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#45]
Pushbullet is a notification service that connects your PC + mobile devices
It is not malicious
I believe this is a FP

"Pushbullet is one of the fastest and easiest way to get links, notes, lists, files, and addresses both from your desktop computer to your mobile device and vice versa. All of this is done from the Pushbullet Android app, the service's Web site, or one of the browser extensions for Chrome or Firefox."

**Comment by ShadowWhisperer** [comment]
Removed. Thanks!
