### ISSUE TITLE
ekr.zdassets.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#49]
Hi,
Blocking this domain breaks ZenDesk (in app help/support)
I was trying to get help on calendar.com through their ZenDesk and blocking this domain broke the "?" button that is supposed to engage the ZenDesk helpdesk
![image](https://user-images.githubusercontent.com/9235633/157506262-8c883914-266b-4a98-b105-7c2e50eba8ba.png)

**Comment by ShadowWhisperer** [comment]
Whitelisted. Thank you!
