### ISSUE TITLE
notifications-pusher.gog.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#50]
Hi,
This domain seems to be required to push notifications out using the Good Old games Galaxy client
I believe this is a FP

**Comment by ShadowWhisperer** [comment]
Does blocking these break friend notifications and Galaxy achievements, or normal push notifications?

```
notifications-pusher.gog.com
notifications.gog.com
```

**Comment by p1r473** [comment]
I haven't received a single notification while these are blocked so I think so :)

**Comment by spirillen** [comment]
> Does blocking these break friend notifications

Unintended funny to read :rofl: as do you have any friends :smiley:
