### ISSUE TITLE
Ever heard of Tranco 1M?

### ISSUE THREAD

**Issue by T145** [ShadowWhisperer/BlockLists#6]
Since you reference Alexa 1M I'd figure you'd love this: https://tranco-list.eu/

**Comment by ShadowWhisperer** [comment]
Acually, that is one that I use!

http://downloads.majestic.com/majestic_million.csv
http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip
https://tranco-list.eu/download/P63J/full
http://s3.amazonaws.com/alexa-static/top-1m.csv.zip

**Comment by T145** [comment]
List Name | URL
--- | --- |
Alexa | https://s3.amazonaws.com/alexa-static/top-1m.csv.zip
Umbrella | https://downloads.majestic.com/majestic_million.csv
Statvoo | https://statvoo.com/dl/top-1million-sites.csv.zip
Openpagerank | https://www.domcop.com/files/top/top10milliondomains.csv.zip
Quantcast | https://toplists.net.in.tum.de/archive/quantcast/quantcast-top-sites-2021-06-25_0900_UTC.txt.xz
Tranco list | https://tranco-list.eu/download/W7X9/full

😉
