### ISSUE TITLE
event.msi.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#60]
Hi,
This domain is used for MSI Afterburner checking for updates. This breaks the update checks
![image](https://user-images.githubusercontent.com/9235633/182439789-0cc30e60-a97b-4c1e-8b0c-154a5f2febc3.png)

**Comment by ShadowWhisperer** [comment]
It has been moved from _Tracking_ to _Bloat_.  Thanks!
