### ISSUE TITLE
FP: escort-dusseldorf.com

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#62]
`escort-dusseldorf.com` is hijacked by `Namecheap.com`

![image](https://user-images.githubusercontent.com/44526987/189099486-a940a567-615d-4c04-9230-89a14892abe7.png)

**Comment by spirillen** [comment]
PS: @ShadowWhisperer you have a post here https://mypdns.org/mypdns/support/-/issues/815

**Comment by ShadowWhisperer** [comment]
Above link results in 404 error. Page is parked, so removed.  Thanks!
