### ISSUE TITLE
Contact!!

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#63]
Hey @ShadowWhisperer are you monitoring https://mypdns.org/ for issues where you are mentioned?

I know there is a comment for you here https://mypdns.org/mypdns/support/-/issues/815#note_5423736 from another user.

------------

Are you still up for sharing known blacklists items?

**Comment by DoRullings** [comment]
Hi!
Sorry, been in an accident and I'm not 100% fit right now to say it politely. Your link to is broken and I can't find the comment right now.
//Thomas

**Comment by spirillen** [comment]
Sad to hear you've been down... hoping you'll be back up soon.

The link however work fine for me

![image](https://user-images.githubusercontent.com/44526987/190961163-fc4210d3-11d6-4c8f-9de1-d139cd8963a1.png)

However you need to be signed in before you can access that issue.

Ho about your ow lists are they kept up to date or are they on a short break?

**Comment by spirillen** [comment]
@ShadowWhisperer / @DoRullings is there somehow something we can do to help you or your project to stay current and alive till you are back on your feet??

Please just let us know and we will see what we can do.

**Comment by ShadowWhisperer** [comment]
I'll check it out, when I have more time

**Comment by ShadowWhisperer** [comment]
Took a few hour to go through them all, but it should be current.
