### ISSUE TITLE
Public-api.wordpress.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#64]
Hi
This is Wordpress's public API
This isnt malicious :)

**Comment by ShadowWhisperer** [comment]
Hey,  
Do you have a specific site or like, that fails to load/work?
`wss://public-api.wordpress.com/pinghub/***`

**Comment by ShadowWhisperer** [comment]
*bump

**Comment by p1r473** [comment]
Yes it had broken something, possibly credly.com (just going by what site I visited right before I opened up the ticket)
I will update this ticket if I figure it out. Until then, I will just whitelist locally.
