### ISSUE TITLE
Redir: 841k8qv38d.ru

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#68]
Found in the ads list https://github.com/ShadowWhisperer/BlockLists/commit/7cfac5ebc52b5dab90906ea2fa8eee6cd507dad8#diff-85e3e9cb63476880e98a7fb2c99f55b1381a8353ce99c3a4239bb908427d955fR290

```
curl -I 841k8qv38d.ru
HTTP/1.1 301 Moved Permanently
Server: nginx/1.18.0
Date: Tue, 22 Nov 2022 23:49:22 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
Location: https://ads.bid/
```

**Comment by ShadowWhisperer** [comment]
That's why it's blocked.
_841k8qv38d.ru_ was observed in use. I don't have the specific URL.
When used on it's own, it redirects to ads.bid. Most of them that redirect to "ads.bid" (that I've seen), when not using the full URL.

**Comment by ShadowWhisperer** [comment]
`841k8qv38d.ru` was observed in use. I don't have the specific URL.  
When used on it's own, it redirects to `ads.bid`. Most of them that redirect to `ads.bid` (that I've seen), when not using the full URL.

**Comment by spirillen** [comment]
True, My intention was to mention you probably wouldn't need the record at blocking ads.bid should solve it, an hence minimize you file size's for Windows users

**Comment by ShadowWhisperer** [comment]
if `http://841k8qv38d.ru/example/adloader.js` is loaded, it loads ads from different locations (or it own location). Blocking `ads.bid` does not prevent `841k8qv38d.ru` from loading ads.
