### ISSUE TITLE
block fly.dev, deno.dev, workers.dev, pages.dev, and web.app

### ISSUE THREAD

**Issue by ignoramous** [ShadowWhisperer/BlockLists#69]
Hi: These qualify for `Free`, I think?

```
fly.dev
deno.dev
workers.dev
pages.dev
web.app
```

**Comment by ShadowWhisperer** [comment]
`deno.dev`   JavaScript Host  - Added to list. Don't see anything (That I know of) that breaks.

`fly.dev` / `fly.io`  Paid  
`workers.dev`  Cloudflare code host (Breaks other legit sites: _serve-cdn-assets.sfd.workers.dev_)  
`pages.dev` Clouflare (Free/Paid)  
`web.app`  Google Firebase  
  
  _Free_ is for sites that are strictly free/don't break other non-free sites/applications. Mainly used internally to remove subdomains from lists.

**Comment by ignoramous** [comment]
Gotcha. Thanks. 

I must point out though that deno.dev and workers.dev serve similar workloads.

I guess some of these belong in *Risks* then?

**Comment by ShadowWhisperer** [comment]
It looks like `deno.dev` is the free version of `workers.dev`.
Domains/subdomains do not appear to be risky.
Google Firebase is being monitored. Mainly used for tracking. Blocked internally. When confirmed, individual domains are added to Github.

**Comment by ignoramous** [comment]
Makes sense. Thanks (:

**Comment by spirillen** [comment]
Regarding `web.app` (Firebase), then I'll just sharing I blacklist it completely for tracking, as it is the only actual purpose of the domain(s)

https://mypdns.org/my-privacy-dns/matrix/-/issues/1884

And the following subdomain are marked as Phishing

```css
restore637908-coinbase-us.web.app   CNAME . ; Phishing
alignmentlidjsonpanz.web.app   CNAME . ; Phishing
```

**Comment by ignoramous** [comment]
@spirillen impressive list. I just got phisphed by website hosted on `web.app`. Sigh. It is really wild wild west out there with all these free hosting services.
