### ISSUE TITLE
shop.app

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#7]
This is a URL shortener service for shopify, and is not malicious
Thanks

**Comment by ShadowWhisperer** [comment]
Thanks! It will be removed from the _tracking_ list, later tonight.

**Comment by p1r473** [comment]
@ShadowWhisperer this is still on your list FYI

**Comment by ShadowWhisperer** [comment]
Oops. Sorry!  I rebuilt how my wildcard works. I initially had two different lists, and merged them into a single list. I must of forgot to remove it from the wildcard list.  Thanks for the heads up!

- Sean H.
