### ISSUE TITLE
False Positive: simplemobile.com

### ISSUE THREAD

**Issue by TPS** [ShadowWhisperer/BlockLists#71]
@ShadowWhisperer simplemobile.com is an MVNO.  Could you determine how it ended up blocked?

**Comment by hagezi** [comment]
https://www.trustpilot.com/review/simplemobile.com

**Comment by ShadowWhisperer** [comment]
I'm not certain how that ended up in there.
Their support may be bad, but they are owned by Verizon, so whitelisted.

`https://www.bestbuy.com/site/simple-mobile-50-prepaid-payment-code-digital/6368105.p?skuId=6368105
https://play.google.com/store/apps/details?id=com.tracfone.simplemobile.myaccount&hl=en_US&gl=US`

Over 200 negative reviews is very bad. That being said, people are more likely to make a negative review when they are angry, but won't make reviews when everything is working great. **I hear complaints almost daily about local internet providers, but nobody tells me when they work great.

Thanks!
