### ISSUE TITLE
vendorlist.dmcdn.net breaks Dailymotion

### ISSUE THREAD

**Issue by alxthaman** [ShadowWhisperer/BlockLists#74]
Hi!

**vendorlist.dmcdn.net** in the **Ads** lists breaks Dailymotion.com

https://www.dailymotion.com/

With the filter activated, the site won't load at all.

**Comment by ShadowWhisperer** [comment]
Hey,

It has been whitelisted. Strange, everything loads fine for me. Tested multiple browsers and systems. Dailymotion worked, but wouldn't play videos, over the VPNs I tested. I see it listed in other spots that blocking it causes issues.

Thanks!
