### ISSUE TITLE
websitepolicies.io

### ISSUE THREAD

**Issue by spirillen** [ShadowWhisperer/BlockLists#83]
`websitepolicies.io` is tracking, not ads, https://0xacab.org/my-privacy-dns/matrix/-/issues/70828

`data/shadowwhisperer/Ads/domain.list:websitepolicies.io`

**Comment by ShadowWhisperer** [comment]
`Create a cookie consent banner - Log in - WebsitePolicies`

**Comment by spirillen** [comment]
Oki doki, adding it as both :smiley:
