### ISSUE TITLE
Explanation of the Raw Lists

### ISSUE THREAD

**Issue by sgtcoder** [ShadowWhisperer/BlockLists#97]
Hi,

I was wondering if you have an explanation of what each of the raw lists do? I am using the raw lists since I find them to better suit my needs.

Additionally, sites like marketo.com break the download form on FreePBX, plus many other blocks coming from Wild Ads.

Here are the blocklists I am using now, but hoping to add more that don't break sites. I wrote a PHP API Call to parse these files and always_nxdomain for Unbound DNS.

https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Ads
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Cryptocurrency
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Malware
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/RAW/Scam

**Comment by ShadowWhisperer** [comment]
**RAW** is the same as the **Lists**, without the comments at the top.

**Ads** is to be used exactly as it is.
**Wild_Ads** is to block everything in the list as *.line

_app-sj14.marketo.com_ has now been whitelisted

**Comment by sgtcoder** [comment]
Thank you for that information. I will give you a list if I find anymore. I have been whitelisting them on my side usually (used another Git Repo list in the past). Yours seems a bit better with the confirmed whitelisting for various sites.
